<div id="top"><font size="+1">
<p><font size="+7" color="#0000FF"><b>Screen shots</b></font></p>
  <a href="Shot1.php">Evaluate</a> &nbsp; &nbsp; 
  <a href="Shot2.php">Insert shade</a> &nbsp; &nbsp;
  <a href="Shot3.php">Insert function</a> &nbsp; &nbsp; 
  <a href="Shot4.php">Insert point series</a> &nbsp; &nbsp; 
  <a href="Shot5.php">Insert trendline</a> &nbsp; &nbsp; 
  <a href="Shot6.php">Add labels</a> &nbsp; &nbsp;
  <a href="Shot7.php">Insert relation</a></font>
</div>
