<p align="center"><font size="+7" color="#0000FF"><b>Screen shots</b></font></p>
<div id="top"><font size="+1">
  <a href="shot1.html" target="PictureFrame">Evaluate</a> &nbsp; &nbsp; 
  <a href="shot2.html" target="PictureFrame">Insert shade</a> &nbsp; &nbsp;
  <a href="shot3.html" target="PictureFrame">Insert function</a> &nbsp; &nbsp; 
  <a href="shot4.html" target="PictureFrame">Insert point series</a> &nbsp; &nbsp; 
  <a href="shot5.html" target="PictureFrame">Insert trendline</a> &nbsp; &nbsp; 
  <a href="shot6.html" target="PictureFrame">Add labels</a> &nbsp; &nbsp;
  <a href="shot7.html" target="PictureFrame">Insert relation</a></font>
</div>
