/* Graph (http://sourceforge.net/projects/graph)
 * Copyright 2010 Ivan Johansen
 *
 * Graph is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or (at
 * your option) any later version.
 */
//---------------------------------------------------------------------------
#include "Graph.h"
#pragma hdrstop
#include "ClassList.h"
#include <WideStrUtils.hpp>
#include <Clipbrd.hpp>
#include <ConvUtils.hpp>
#include <Mask.hpp>
#include <IniFiles.hpp>
#include <Grids.hpp>
#include <DateUtils.hpp>
#include <Masks.hpp>
#include <Generics.Collections.hpp>
#include <Registry.hpp>
#include <VarUtils.hpp>
#include <DockTabset.hpp>
#include <Zlib.hpp>
#include <WinSock.hpp>
#include <AppEvnts.hpp>
#include <CategoryButtons.hpp>
#include <Buttons.hpp>
#include <Types.hpp>
#include <StdActns.hpp>
#include <ExtActns.hpp>
#include <ButtonGroup.hpp>
#include <IOUtils.hpp>
#include <ValEdit.hpp>
#include <AnsiStrings.hpp>
#include <IMouse.hpp>
#include <Diagnostics.hpp>
#include <Themes.hpp>
#include <Character.hpp>
#include <SystVar.h>
#include <WideStrings.hpp>
//---------------------------------------------------------------------------
#pragma package(smart_init)
namespace Python
{
struct TClassList
{
	const wchar_t *ClassName;
	TTypeInfo *TypeInfo;
};

TClassList ClassList[] =
{
	{L"AnsiChar", __delphirtti(System::AnsiChar)},
	{L"AnsiString", __delphirtti(System::AnsiString)},
	{L"Boolean", __delphirtti(System::Boolean)},
	{L"Byte", __delphirtti(System::Byte)},
	{L"ByteBool", __delphirtti(System::ByteBool)},
	{L"Cardinal", __delphirtti(System::Cardinal)},
	{L"Char", __delphirtti(System::Char)},
	{L"CharSet", __delphirtti(Widestrutils::CharSet)},
//  {L"Comp", __delphirtti(System::Comp)},
//  {L"CppLongInt", __delphirtti(System::CppLongInt)},
//  {L"CppULongInt", __delphirtti(System::CppULongInt)},
	{L"Currency", __delphirtti(System::Currency)},
//  {L"DelayLoadInfo", __delphirtti(System::DelayLoadInfo)},
//  {L"DelayLoadProc", __delphirtti(System::DelayLoadProc)},
//  {L"DelayedLoadHook", __delphirtti(System::DelayedLoadHook)},
  {L"Double", __delphirtti(System::Double)},
  {L"EAbort", __delphirtti(Sysutils::EAbort)},
  {L"EAbstractError", __delphirtti(Sysutils::EAbstractError)},
  {L"EAccessViolation", __delphirtti(Sysutils::EAccessViolation)},
  {L"EArgumentException", __delphirtti(Sysutils::EArgumentException)},
  {L"EArgumentNilException", __delphirtti(Sysutils::EArgumentNilException)},
  {L"EArgumentOutOfRangeException", __delphirtti(Sysutils::EArgumentOutOfRangeException)},
  {L"EAssertionFailed", __delphirtti(Sysutils::EAssertionFailed)},
  {L"EBitsError", __delphirtti(Classes::EBitsError)},
  {L"EClassNotFound", __delphirtti(Classes::EClassNotFound)},
  {L"EClipboardException", __delphirtti(Clipbrd::EClipboardException)},
  {L"EComponentError", __delphirtti(Classes::EComponentError)},
  {L"EControlC", __delphirtti(Sysutils::EControlC)},
  {L"EConversionError", __delphirtti(Convutils::EConversionError)},
  {L"EConvertError", __delphirtti(Sysutils::EConvertError)},
  {L"EDBEditError", __delphirtti(Mask::EDBEditError)},
	{L"EDirectoryNotFoundException", __delphirtti(Sysutils::EDirectoryNotFoundException)},
  {L"EDivByZero", __delphirtti(Sysutils::EDivByZero)},
	{L"EEncodingError", __delphirtti(Sysutils::EEncodingError)},
  {L"EExternal", __delphirtti(Sysutils::EExternal)},
  {L"EExternalException", __delphirtti(Sysutils::EExternalException)},
  {L"EFCreateError", __delphirtti(Classes::EFCreateError)},
  {L"EFOpenError", __delphirtti(Classes::EFOpenError)},
  {L"EFileNotFoundException", __delphirtti(Sysutils::EFileNotFoundException)},
  {L"EFileStreamError", __delphirtti(Classes::EFileStreamError)},
  {L"EFilerError", __delphirtti(Classes::EFilerError)},
  {L"EGestureException", __delphirtti(Controls::EGestureException)},
	{L"EGridPanelException", __delphirtti(Extctrls::EGridPanelException)},
  {L"EHeapException", __delphirtti(Sysutils::EHeapException)},
  {L"EHelpSystemException", __delphirtti(Helpintfs::EHelpSystemException)},
  {L"EInOutError", __delphirtti(Sysutils::EInOutError)},
  {L"EIniFileException", __delphirtti(Inifiles::EIniFileException)},
  {L"EIntError", __delphirtti(Sysutils::EIntError)},
  {L"EIntOverflow", __delphirtti(Sysutils::EIntOverflow)},
  {L"EIntfCastError", __delphirtti(Sysutils::EIntfCastError)},
  {L"EInvalidArgument", __delphirtti(Math::EInvalidArgument)},
  {L"EInvalidCast", __delphirtti(Sysutils::EInvalidCast)},
  {L"EInvalidContainer", __delphirtti(Sysutils::EInvalidContainer)},
  {L"EInvalidGraphic", __delphirtti(Graphics::EInvalidGraphic)},
  {L"EInvalidGraphicOperation", __delphirtti(Graphics::EInvalidGraphicOperation)},
  {L"EInvalidGridOperation", __delphirtti(Grids::EInvalidGridOperation)},
  {L"EInvalidImage", __delphirtti(Classes::EInvalidImage)},
  {L"EInvalidInsert", __delphirtti(Sysutils::EInvalidInsert)},
  {L"EInvalidOp", __delphirtti(Sysutils::EInvalidOp)},
  {L"EInvalidOpException", __delphirtti(Sysutils::EInvalidOpException)},
	{L"EInvalidOperation", __delphirtti(Classes::EInvalidOperation)},
  {L"EInvalidPointer", __delphirtti(Sysutils::EInvalidPointer)},
	{L"EListError", __delphirtti(Classes::EListError)},
  {L"ELocalTimeInvalid", __delphirtti(Dateutils::ELocalTimeInvalid)},
  {L"ELockException", __delphirtti(Syncobjs::ELockException)},
  {L"ELockRecursionException", __delphirtti(Syncobjs::ELockRecursionException)},
  {L"EMaskException", __delphirtti(Masks::EMaskException)},
  {L"EMathError", __delphirtti(Sysutils::EMathError)},
  {L"EMenuError", __delphirtti(Menus::EMenuError)},
  {L"EMethodNotFound", __delphirtti(Classes::EMethodNotFound)},
	{L"EMonitor", __delphirtti(Sysutils::EMonitor)},
  {L"EMonitorLockException", __delphirtti(Sysutils::EMonitorLockException)},
  {L"ENoConstructException", __delphirtti(Sysutils::ENoConstructException)},
  {L"ENoMonitorSupportException", __delphirtti(Sysutils::ENoMonitorSupportException)},
  {L"ENotImplemented", __delphirtti(Sysutils::ENotImplemented)},
  {L"ENotSupportedException", __delphirtti(Generics_collections::ENotSupportedException)},
  {L"EOSError", __delphirtti(Sysutils::EOSError)},
  {L"EOutOfMemory", __delphirtti(Sysutils::EOutOfMemory)},
  {L"EOutOfResources", __delphirtti(Classes::EOutOfResources)},
  {L"EOverflow", __delphirtti(Sysutils::EOverflow)},
  {L"EPackageError", __delphirtti(Sysutils::EPackageError)},
  {L"EParserError", __delphirtti(Classes::EParserError)},
  {L"EPathTooLongException", __delphirtti(Sysutils::EPathTooLongException)},
  {L"EPlatformVersionException", __delphirtti(Dialogs::EPlatformVersionException)},
  {L"EPrinter", __delphirtti(Printers::EPrinter)},
  {L"EPrivilege", __delphirtti(Sysutils::EPrivilege)},
  {L"EProgrammerNotFound", __delphirtti(Sysutils::EProgrammerNotFound)},
  {L"EPropReadOnly", __delphirtti(Sysutils::EPropReadOnly)},
  {L"EPropWriteOnly", __delphirtti(Sysutils::EPropWriteOnly)},
	{L"ERangeError", __delphirtti(Sysutils::ERangeError)},
  {L"EReadError", __delphirtti(Classes::EReadError)},
	{L"ERegistryException", __delphirtti(Registry::ERegistryException)},
  {L"EResNotFound", __delphirtti(Classes::EResNotFound)},
  {L"ESafeArrayBoundsError", __delphirtti(Varutils::ESafeArrayBoundsError)},
  {L"ESafeArrayCreateError", __delphirtti(Varutils::ESafeArrayCreateError)},
  {L"ESafeArrayError", __delphirtti(Varutils::ESafeArrayError)},
  {L"ESafeArrayLockedError", __delphirtti(Varutils::ESafeArrayLockedError)},
  {L"ESafecallException", __delphirtti(Sysutils::ESafecallException)},
	{L"EStackOverflow", __delphirtti(Sysutils::EStackOverflow)},
	{L"EStreamError", __delphirtti(Classes::EStreamError)},
  {L"EStringListError", __delphirtti(Classes::EStringListError)},
  {L"ESyncObjectException", __delphirtti(Syncobjs::ESyncObjectException)},
  {L"ETabDockException", __delphirtti(Docktabset::ETabDockException)},
  {L"EThread", __delphirtti(Classes::EThread)},
  {L"EThreadExternalException", __delphirtti(Classes::EThreadExternalException)},
  {L"EUnderflow", __delphirtti(Sysutils::EUnderflow)},
  {L"EVariantArrayCreateError", __delphirtti(Variants::EVariantArrayCreateError)},
  {L"EVariantArrayLockedError", __delphirtti(Variants::EVariantArrayLockedError)},
  {L"EVariantBadIndexError", __delphirtti(Variants::EVariantBadIndexError)},
  {L"EVariantBadVarTypeError", __delphirtti(Variants::EVariantBadVarTypeError)},
  {L"EVariantDispatchError", __delphirtti(Variants::EVariantDispatchError)},
  {L"EVariantError", __delphirtti(Sysutils::EVariantError)},
  {L"EVariantInvalidArgError", __delphirtti(Variants::EVariantInvalidArgError)},
  {L"EVariantInvalidNullOpError", __delphirtti(Variants::EVariantInvalidNullOpError)},
  {L"EVariantInvalidOpError", __delphirtti(Variants::EVariantInvalidOpError)},
  {L"EVariantNotAnArrayError", __delphirtti(Variants::EVariantNotAnArrayError)},
  {L"EVariantNotImplError", __delphirtti(Variants::EVariantNotImplError)},
  {L"EVariantOutOfMemoryError", __delphirtti(Variants::EVariantOutOfMemoryError)},
	{L"EVariantOverflowError", __delphirtti(Variants::EVariantOverflowError)},
	{L"EVariantRangeCheckError", __delphirtti(Variants::EVariantRangeCheckError)},
	{L"EVariantTypeCastError", __delphirtti(Variants::EVariantTypeCastError)},
	{L"EVariantUnexpectedError", __delphirtti(Variants::EVariantUnexpectedError)},
	{L"EWin32Error", __delphirtti(Sysutils::EWin32Error)},
	{L"EWriteError", __delphirtti(Classes::EWriteError)},
	{L"EZCompressionError", __delphirtti(Zlib::EZCompressionError)},
	{L"EZDecompressionError", __delphirtti(Zlib::EZDecompressionError)},
	{L"EZLibError", __delphirtti(Zlib::EZLibError)},
	{L"EZeroDivide", __delphirtti(Sysutils::EZeroDivide)},
//	{L"ExceptClass", __delphirtti(Sysutils::ExceptClass)},
	{L"Exception", __delphirtti(Sysutils::Exception)},
	{L"Extended", __delphirtti(System::Extended)},
//	{L"GetPackageInfoTable", __delphirtti(System::GetPackageInfoTable)},
//  {L"HRESULT", __delphirtti(System::HRESULT)},
//  {L"ImgDelayDescr", __delphirtti(System::ImgDelayDescr)},
//  {L"Int64", __delphirtti(System::Int64)},
//  {L"Int64Rec", __delphirtti(Sysutils::Int64Rec)},
	{L"Integer", __delphirtti(System::Integer)},
//	{L"IntegerArray", __delphirtti(System::IntegerArray)},
	{L"LongBool", __delphirtti(System::LongBool)},
//  {L"LongRec", __delphirtti(Sysutils::LongRec)},
//  {L"NativeInt", __delphirtti(System::NativeInt)},
//  {L"NativeUInt", __delphirtti(System::NativeUInt)},
	{L"NaturalNumber", __delphirtti(Extctrls::NaturalNumber)},
	{L"OleVariant", __delphirtti(System::OleVariant)},
//	{L"Openstring", __delphirtti(System::Openstring)},
	{L"PackageInfo", __delphirtti(System::PackageInfo)},
//	{L"PackageInfoTable", __delphirtti(System::PackageInfoTable)},
//	{L"PackageUnitEntry", __delphirtti(System::PackageUnitEntry)},
	{L"Pointer", __delphirtti(System::Pointer)},
	{L"PointerArray", __delphirtti(System::PointerArray)},
	{L"RawByteString", __delphirtti(System::RawByteString)},
//  {L"Real", __delphirtti(System::Real)},
	{L"ShortInt", __delphirtti(System::ShortInt)},
//  {L"ShortString", __delphirtti(System::ShortString)},
	{L"Single", __delphirtti(System::Single)},
	{L"SmallInt", __delphirtti(System::SmallInt)},
//	{L"SunB", __delphirtti(Winsock::SunB)},
//  {L"SunW", __delphirtti(Winsock::SunW)},
	{L"TAction", __delphirtti(Actnlist::TAction)},
	{L"TActionEvent", __delphirtti(Actnlist::TActionEvent)},
	{L"TActionLink", __delphirtti(Actnlist::TActionLink)},
	{L"TActionLinkClass", __delphirtti(Actnlist::TActionLinkClass)},
	{L"TActionList", __delphirtti(Actnlist::TActionList)},
	{L"TActionListEnumerator", __delphirtti(Actnlist::TActionListEnumerator)},
	{L"TActionListState", __delphirtti(Actnlist::TActionListState)},
	{L"TActiveFormBorderStyle", __delphirtti(Forms::TActiveFormBorderStyle)},
	{L"TActiveXRegType", __delphirtti(Classes::TActiveXRegType)},
  {L"TAdvancedMenuDrawItemEvent", __delphirtti(Menus::TAdvancedMenuDrawItemEvent)},
  {L"TAggregatedObject", __delphirtti(System::TAggregatedObject)},
  {L"TAlign", __delphirtti(Controls::TAlign)},
//  {L"TAlignInfo", __delphirtti(Controls::TAlignInfo)},
  {L"TAlignInsertBeforeEvent", __delphirtti(Controls::TAlignInsertBeforeEvent)},
  {L"TAlignPositionEvent", __delphirtti(Controls::TAlignPositionEvent)},
  {L"TAlignSet", __delphirtti(Controls::TAlignSet)},
	{L"TAlignment", __delphirtti(Classes::TAlignment)},
  {L"TAlphaFormat", __delphirtti(Graphics::TAlphaFormat)},
	{L"TAncestorNotFoundEvent", __delphirtti(Classes::TAncestorNotFoundEvent)},
  {L"TAnchorKind", __delphirtti(Controls::TAnchorKind)},
  {L"TAnchors", __delphirtti(Controls::TAnchors)},
  {L"TAnimateWindowProc", __delphirtti(Controls::TAnimateWindowProc)},
  {L"TAnyProc", __delphirtti(Variants::TAnyProc)},
  {L"TApplication", __delphirtti(Forms::TApplication)},
	{L"TApplicationEvents", __delphirtti(Appevnts::TApplicationEvents)},
  {L"TArray", __delphirtti(Generics_collections::TArray)},
  {L"TArrowType", __delphirtti(Graphutil::TArrowType)},
  {L"TAssertErrorProc", __delphirtti(System::TAssertErrorProc)},
	{L"TBalloonFlags", __delphirtti(Extctrls::TBalloonFlags)},
  {L"TBalloonHint", __delphirtti(Controls::TBalloonHint)},
  {L"TBalloonHintIcon", __delphirtti(Controls::TBalloonHintIcon)},
  {L"TBalloonHintIconSize", __delphirtti(Controls::TBalloonHintIconSize)},
  {L"TBalloonHintStyle", __delphirtti(Controls::TBalloonHintStyle)},
  {L"TBandDragEvent", __delphirtti(Extctrls::TBandDragEvent)},
  {L"TBandDrawingStyle", __delphirtti(Extctrls::TBandDrawingStyle)},
  {L"TBandInfoEvent", __delphirtti(Extctrls::TBandInfoEvent)},
  {L"TBandMoveEvent", __delphirtti(Extctrls::TBandMoveEvent)},
  {L"TBandPaintEvent", __delphirtti(Extctrls::TBandPaintEvent)},
  {L"TBandPaintOption", __delphirtti(Extctrls::TBandPaintOption)},
  {L"TBandPaintOptions", __delphirtti(Extctrls::TBandPaintOptions)},
  {L"TBaseButtonItem", __delphirtti(Categorybuttons::TBaseButtonItem)},
  {L"TBaseButtonItemClass", __delphirtti(Categorybuttons::TBaseButtonItemClass)},
  {L"TBaseDragControlObject", __delphirtti(Controls::TBaseDragControlObject)},
  {L"TBaseItem", __delphirtti(Categorybuttons::TBaseItem)},
  {L"TBasicAction", __delphirtti(Classes::TBasicAction)},
	{L"TBasicActionClass", __delphirtti(Classes::TBasicActionClass)},
  {L"TBasicActionLink", __delphirtti(Classes::TBasicActionLink)},
	{L"TBasicActionLinkClass", __delphirtti(Classes::TBasicActionLinkClass)},
  {L"TBeginBandMoveEvent", __delphirtti(Extctrls::TBeginBandMoveEvent)},
  {L"TBevel", __delphirtti(Extctrls::TBevel)},
  {L"TBevelCut", __delphirtti(Controls::TBevelCut)},
  {L"TBevelEdge", __delphirtti(Controls::TBevelEdge)},
	{L"TBevelEdges", __delphirtti(Controls::TBevelEdges)},
  {L"TBevelKind", __delphirtti(Controls::TBevelKind)},
  {L"TBevelShape", __delphirtti(Extctrls::TBevelShape)},
  {L"TBevelStyle", __delphirtti(Extctrls::TBevelStyle)},
  {L"TBevelWidth", __delphirtti(Controls::TBevelWidth)},
	{L"TBiDiMode", __delphirtti(Classes::TBiDiMode)},
  {L"TBigEndianUnicodeEncoding", __delphirtti(Sysutils::TBigEndianUnicodeEncoding)},
  {L"TBinaryReader", __delphirtti(Classes::TBinaryReader)},
  {L"TBinaryWriter", __delphirtti(Classes::TBinaryWriter)},
  {L"TBitBtn", __delphirtti(Buttons::TBitBtn)},
  {L"TBitBtnActionLink", __delphirtti(Buttons::TBitBtnActionLink)},
  {L"TBitBtnKind", __delphirtti(Buttons::TBitBtnKind)},
  {L"TBitOffset", __delphirtti(Syncobjs::TBitOffset)},
  {L"TBitmap", __delphirtti(Graphics::TBitmap)},
  {L"TBitmapHandleType", __delphirtti(Graphics::TBitmapHandleType)},
  {L"TBitmapImage", __delphirtti(Graphics::TBitmapImage)},
  {L"TBits", __delphirtti(Classes::TBits)},
	{L"TBooleanDynArray", __delphirtti(System::TBooleanDynArray)},
  {L"TBooleanToStringRule", __delphirtti(Variants::TBooleanToStringRule)},
  {L"TBorderIcon", __delphirtti(Forms::TBorderIcon)},
  {L"TBorderIcons", __delphirtti(Forms::TBorderIcons)},
  {L"TBorderStyle", __delphirtti(Forms::TBorderStyle)},
	{L"TBorderWidth", __delphirtti(Controls::TBorderWidth)},
  {L"TBoundArray", __delphirtti(System::TBoundArray)},
	{L"TBoundLabel", __delphirtti(Extctrls::TBoundLabel)},
  {L"TBrowseForFolder", __delphirtti(Stdactns::TBrowseForFolder)},
  {L"TBrowseForFolderCallbackEvent", __delphirtti(Stdactns::TBrowseForFolderCallbackEvent)},
  {L"TBrowseForFolderOption", __delphirtti(Stdactns::TBrowseForFolderOption)},
	{L"TBrowseOptions", __delphirtti(Stdactns::TBrowseOptions)},
  {L"TBrowseURL", __delphirtti(Extactns::TBrowseURL)},
  {L"TBrush", __delphirtti(Graphics::TBrush)},
//  {L"TBrushData", __delphirtti(Graphics::TBrushData)},
  {L"TBrushRecall", __delphirtti(Graphics::TBrushRecall)},
  {L"TBrushStyle", __delphirtti(Graphics::TBrushStyle)},
//  {L"TBucket", __delphirtti(Contnrs::TBucket)},
  {L"TBucketArray", __delphirtti(Contnrs::TBucketArray)},
  {L"TBucketEvent", __delphirtti(Contnrs::TBucketEvent)},
//  {L"TBucketItem", __delphirtti(Contnrs::TBucketItem)},
  {L"TBucketItemArray", __delphirtti(Contnrs::TBucketItemArray)},
  {L"TBucketList", __delphirtti(Contnrs::TBucketList)},
  {L"TBucketListSizes", __delphirtti(Contnrs::TBucketListSizes)},
  {L"TBucketProc", __delphirtti(Contnrs::TBucketProc)},
  {L"TButton", __delphirtti(Stdctrls::TButton)},
  {L"TButtonActionLink", __delphirtti(Stdctrls::TButtonActionLink)},
  {L"TButtonActionLinkClass", __delphirtti(Stdctrls::TButtonActionLinkClass)},
  {L"TButtonCategories", __delphirtti(Categorybuttons::TButtonCategories)},
  {L"TButtonCategoriesClass", __delphirtti(Categorybuttons::TButtonCategoriesClass)},
  {L"TButtonCategory", __delphirtti(Categorybuttons::TButtonCategory)},
  {L"TButtonCategoryClass", __delphirtti(Categorybuttons::TButtonCategoryClass)},
  {L"TButtonCollection", __delphirtti(Categorybuttons::TButtonCollection)},
  {L"TButtonControl", __delphirtti(Stdctrls::TButtonControl)},
	{L"TButtonDrawState", __delphirtti(Categorybuttons::TButtonDrawState)},
  {L"TButtonGroup", __delphirtti(Buttongroup::TButtonGroup)},
	{L"TButtonItem", __delphirtti(Categorybuttons::TButtonItem)},
  {L"TButtonItemActionLink", __delphirtti(Categorybuttons::TButtonItemActionLink)},
  {L"TButtonItemActionLinkClass", __delphirtti(Categorybuttons::TButtonItemActionLinkClass)},
	{L"TButtonItemClass", __delphirtti(Categorybuttons::TButtonItemClass)},
  {L"TButtonLayout", __delphirtti(Buttons::TButtonLayout)},
  {L"TButtonState", __delphirtti(Buttons::TButtonState)},
  {L"TButtonStyle", __delphirtti(Buttons::TButtonStyle)},
  {L"TButtonedEdit", __delphirtti(Extctrls::TButtonedEdit)},
//  {L"TByteArray", __delphirtti(Sysutils::TByteArray)},
//  {L"TByteDynArray", __delphirtti(Types::TByteDynArray)},
	{L"TBytesStream", __delphirtti(Classes::TBytesStream)},
//  {L"TCMCancelMode", __delphirtti(Controls::TCMCancelMode)},
//  {L"TCMChanged", __delphirtti(Controls::TCMChanged)},
//  {L"TCMChildKey", __delphirtti(Controls::TCMChildKey)},
//  {L"TCMControlChange", __delphirtti(Controls::TCMControlChange)},
//  {L"TCMControlListChange", __delphirtti(Controls::TCMControlListChange)},
//  {L"TCMControlListChanging", __delphirtti(Controls::TCMControlListChanging)},
//	{L"TCMCreatePopup", __delphirtti(Controls::TCMCreatePopup)},
//	{L"TCMDockClient", __delphirtti(Controls::TCMDockClient)},
//	{L"TCMDockNotification", __delphirtti(Controls::TCMDockNotification)},
//	{L"TCMDrag", __delphirtti(Controls::TCMDrag)},
//	{L"TCMFloat", __delphirtti(Controls::TCMFloat)},
//	{L"TCMFocusChanged", __delphirtti(Controls::TCMFocusChanged)},
//	{L"TCMGesture", __delphirtti(Controls::TCMGesture)},
//	{L"TCMHintShow", __delphirtti(Controls::TCMHintShow)},
//	{L"TCMHintShowPause", __delphirtti(Forms::TCMHintShowPause)},
//	{L"TCMMouseActivate", __delphirtti(Controls::TCMMouseActivate)},
//	{L"TCMMouseWheel", __delphirtti(Controls::TCMMouseWheel)},
//	{L"TCMParentFontChanged", __delphirtti(Controls::TCMParentFontChanged)},
//	{L"TCMPopupHWndDestroy", __delphirtti(Controls::TCMPopupHWndDestroy)},
//	{L"TCMUnDockClient", __delphirtti(Controls::TCMUnDockClient)},
//	{L"TCVModInfo", __delphirtti(System::TCVModInfo)},
//	{L"TCallDesc", __delphirtti(System::TCallDesc)},
	{L"TCanResizeEvent", __delphirtti(Controls::TCanResizeEvent)},
	{L"TCanvas", __delphirtti(Graphics::TCanvas)},
	{L"TCanvasOrientation", __delphirtti(Graphics::TCanvasOrientation)},
	{L"TCanvasState", __delphirtti(Graphics::TCanvasState)},
	{L"TCanvasStates", __delphirtti(Graphics::TCanvasStates)},
	{L"TCaption", __delphirtti(Controls::TCaption)},
	{L"TCaptionedDockTree", __delphirtti(Captioneddocktree::TCaptionedDockTree)},
	{L"TCaptionedDockTreeClass", __delphirtti(Captioneddocktree::TCaptionedDockTreeClass)},
	{L"TCaptionedTabDockTree", __delphirtti(Docktabset::TCaptionedTabDockTree)},
//  {L"TCardinalDynArray", __delphirtti(Types::TCardinalDynArray)},
	{L"TCatButtonCancelEditEvent", __delphirtti(Categorybuttons::TCatButtonCancelEditEvent)},
	{L"TCatButtonCategoryEvent", __delphirtti(Categorybuttons::TCatButtonCategoryEvent)},
	{L"TCatButtonCopyEvent", __delphirtti(Categorybuttons::TCatButtonCopyEvent)},
	{L"TCatButtonDrawEvent", __delphirtti(Categorybuttons::TCatButtonDrawEvent)},
	{L"TCatButtonDrawIconEvent", __delphirtti(Categorybuttons::TCatButtonDrawIconEvent)},
	{L"TCatButtonEditedEvent", __delphirtti(Categorybuttons::TCatButtonEditedEvent)},
	{L"TCatButtonEditingEvent", __delphirtti(Categorybuttons::TCatButtonEditingEvent)},
	{L"TCatButtonEvent", __delphirtti(Categorybuttons::TCatButtonEvent)},
	{L"TCatButtonFlow", __delphirtti(Categorybuttons::TCatButtonFlow)},
	{L"TCatButtonGetHint", __delphirtti(Categorybuttons::TCatButtonGetHint)},
	{L"TCatButtonOptions", __delphirtti(Categorybuttons::TCatButtonOptions)},
	{L"TCatButtonReorderEvent", __delphirtti(Categorybuttons::TCatButtonReorderEvent)},
	{L"TCategoryButtons", __delphirtti(Categorybuttons::TCategoryButtons)},
	{L"TCategoryCollapseEvent", __delphirtti(Categorybuttons::TCategoryCollapseEvent)},
	{L"TCategoryPanel", __delphirtti(Extctrls::TCategoryPanel)},
	{L"TCategoryPanelClass", __delphirtti(Extctrls::TCategoryPanelClass)},
	{L"TCategoryPanelGroup", __delphirtti(Extctrls::TCategoryPanelGroup)},
  {L"TCategoryPanelSurface", __delphirtti(Extctrls::TCategoryPanelSurface)},
  {L"TCategoryPanelSurfaceClass", __delphirtti(Extctrls::TCategoryPanelSurfaceClass)},
  {L"TCategoryReorderEvent", __delphirtti(Categorybuttons::TCategoryReorderEvent)},
  {L"TCellCollection", __delphirtti(Extctrls::TCellCollection)},
  {L"TCellItem", __delphirtti(Extctrls::TCellItem)},
  {L"TCellSpan", __delphirtti(Extctrls::TCellSpan)},
  {L"TChangeLink", __delphirtti(Imglist::TChangeLink)},
//  {L"TCharSearch", __delphirtti(Sysutils::TCharSearch)},
//  {L"TCharacter", __delphirtti(Character::TCharacter)},
  {L"TCheckBox", __delphirtti(Stdctrls::TCheckBox)},
  {L"TCheckBoxState", __delphirtti(Stdctrls::TCheckBoxState)},
  {L"TChunkStatus", __delphirtti(System::TChunkStatus)},
  {L"TClass", __delphirtti(System::TClass)},
  {L"TClassFinder", __delphirtti(Classes::TClassFinder)},
//  {L"TClassHelperBase", __delphirtti(System::TClassHelperBase)},
//  {L"TClassHelperBaseClass", __delphirtti(System::TClassHelperBaseClass)},
  {L"TClassList", __delphirtti(Contnrs::TClassList)},
  {L"TClipboard", __delphirtti(Clipbrd::TClipboard)},
  {L"TCloseAction", __delphirtti(Forms::TCloseAction)},
  {L"TCloseEvent", __delphirtti(Forms::TCloseEvent)},
  {L"TCloseQueryEvent", __delphirtti(Forms::TCloseQueryEvent)},
  {L"TCmdLineSwitchType", __delphirtti(Sysutils::TCmdLineSwitchType)},
  {L"TCmdLineSwitchTypes", __delphirtti(Sysutils::TCmdLineSwitchTypes)},
  {L"TCollection", __delphirtti(Classes::TCollection)},
  {L"TCollectionEnumerator", __delphirtti(Classes::TCollectionEnumerator)},
	{L"TCollectionItem", __delphirtti(Classes::TCollectionItem)},
  {L"TCollectionItemClass", __delphirtti(Classes::TCollectionItemClass)},
	{L"TCollectionNotification", __delphirtti(Generics_collections::TCollectionNotification)},
  {L"TColor", __delphirtti(Graphics::TColor)},
  {L"TColorArray", __delphirtti(Graphutil::TColorArray)},
  {L"TColorArraySortType", __delphirtti(Graphutil::TColorArraySortType)},
  {L"TColorBox", __delphirtti(Extctrls::TColorBox)},
  {L"TColorBoxStyle", __delphirtti(Extctrls::TColorBoxStyle)},
  {L"TColorBoxStyles", __delphirtti(Extctrls::TColorBoxStyles)},
  {L"TColorDepth", __delphirtti(Imglist::TColorDepth)},
  {L"TColorDialog", __delphirtti(Dialogs::TColorDialog)},
  {L"TColorDialogOption", __delphirtti(Dialogs::TColorDialogOption)},
  {L"TColorDialogOptions", __delphirtti(Dialogs::TColorDialogOptions)},
  {L"TColorListBox", __delphirtti(Extctrls::TColorListBox)},
  {L"TColorSelect", __delphirtti(Stdactns::TColorSelect)},
  {L"TColumnCollection", __delphirtti(Extctrls::TColumnCollection)},
  {L"TColumnItem", __delphirtti(Extctrls::TColumnItem)},
  {L"TComboBox", __delphirtti(Stdctrls::TComboBox)},
  {L"TComboBoxStyle", __delphirtti(Stdctrls::TComboBoxStyle)},
  {L"TCommonDialog", __delphirtti(Dialogs::TCommonDialog)},
  {L"TCommonDialogAction", __delphirtti(Stdactns::TCommonDialogAction)},
  {L"TCommonDialogClass", __delphirtti(Stdactns::TCommonDialogClass)},
  {L"TCompareTextProc", __delphirtti(Strutils::TCompareTextProc)},
  {L"TComponent", __delphirtti(Classes::TComponent)},
  {L"TComponentClass", __delphirtti(Classes::TComponentClass)},
  {L"TComponentEnumerator", __delphirtti(Classes::TComponentEnumerator)},
  {L"TComponentList", __delphirtti(Contnrs::TComponentList)},
  {L"TComponentName", __delphirtti(Classes::TComponentName)},
  {L"TComponentState", __delphirtti(Classes::TComponentState)},
	{L"TComponentStyle", __delphirtti(Classes::TComponentStyle)},
	{L"TCompressionLevel", __delphirtti(Zlib::TCompressionLevel)},
  {L"TConditionVariableCS", __delphirtti(Syncobjs::TConditionVariableCS)},
  {L"TConditionVariableHelper", __delphirtti(Syncobjs::TConditionVariableHelper)},
  {L"TConditionVariableMutex", __delphirtti(Syncobjs::TConditionVariableMutex)},
  {L"TConstrainedResizeEvent", __delphirtti(Controls::TConstrainedResizeEvent)},
  {L"TConstraintSize", __delphirtti(Controls::TConstraintSize)},
  {L"TContainedAction", __delphirtti(Actnlist::TContainedAction)},
  {L"TContainedActionClass", __delphirtti(Actnlist::TContainedActionClass)},
  {L"TContainedObject", __delphirtti(System::TContainedObject)},
  {L"TContextPopupEvent", __delphirtti(Controls::TContextPopupEvent)},
  {L"TControl", __delphirtti(Controls::TControl)},
  {L"TControlAction", __delphirtti(Controls::TControlAction)},
  {L"TControlActionLink", __delphirtti(Controls::TControlActionLink)},
  {L"TControlActionLinkClass", __delphirtti(Controls::TControlActionLinkClass)},
  {L"TControlBar", __delphirtti(Extctrls::TControlBar)},
  {L"TControlCanvas", __delphirtti(Controls::TControlCanvas)},
  {L"TControlClass", __delphirtti(Controls::TControlClass)},
  {L"TControlCollection", __delphirtti(Extctrls::TControlCollection)},
  {L"TControlItem", __delphirtti(Extctrls::TControlItem)},
//  {L"TControlListItem", __delphirtti(Controls::TControlListItem)},
  {L"TControlScrollBar", __delphirtti(Forms::TControlScrollBar)},
  {L"TControlState", __delphirtti(Controls::TControlState)},
  {L"TControlStyle", __delphirtti(Controls::TControlStyle)},
  {L"TConvFamily", __delphirtti(Convutils::TConvFamily)},
  {L"TConvFamilyArray", __delphirtti(Convutils::TConvFamilyArray)},
  {L"TConvType", __delphirtti(Convutils::TConvType)},
  {L"TConvTypeArray", __delphirtti(Convutils::TConvTypeArray)},
  {L"TConvTypeFactor", __delphirtti(Convutils::TConvTypeFactor)},
	{L"TConvTypeInfo", __delphirtti(Convutils::TConvTypeInfo)},
  {L"TConvTypeList", __delphirtti(Convutils::TConvTypeList)},
  {L"TConvTypeProcs", __delphirtti(Convutils::TConvTypeProcs)},
  {L"TConversionProc", __delphirtti(Convutils::TConversionProc)},
  {L"TCornerEdge", __delphirtti(Extctrls::TCornerEdge)},
  {L"TCountdownEvent", __delphirtti(Syncobjs::TCountdownEvent)},
  {L"TCreateComponentEvent", __delphirtti(Classes::TCreateComponentEvent)},
//  {L"TCreateParams", __delphirtti(Controls::TCreateParams)},
  {L"TCriticalSection", __delphirtti(Syncobjs::TCriticalSection)},
  {L"TCriticalSectionHelper", __delphirtti(Syncobjs::TCriticalSectionHelper)},
  {L"TCursor", __delphirtti(Controls::TCursor)},
//  {L"TCursorOrIcon", __delphirtti(Graphics::TCursorOrIcon)},
//  {L"TCursorRec", __delphirtti(Forms::TCursorRec)},
  {L"TCustomAction", __delphirtti(Actnlist::TCustomAction)},
  {L"TCustomActionList", __delphirtti(Actnlist::TCustomActionList)},
  {L"TCustomActiveForm", __delphirtti(Forms::TCustomActiveForm)},
  {L"TCustomApplicationEvents", __delphirtti(Appevnts::TCustomApplicationEvents)},
  {L"TCustomAttribute", __delphirtti(System::TCustomAttribute)},
	{L"TCustomBucketList", __delphirtti(Contnrs::TCustomBucketList)},
  {L"TCustomButton", __delphirtti(Stdctrls::TCustomButton)},
//  {L"TButtonStyle", __delphirtti(Stdctrls::TCustomButton::TCustomButton::TButtonStyle)},
  {L"TCustomButtonedEdit", __delphirtti(Extctrls::TCustomButtonedEdit)},
  {L"TCustomCanvas", __delphirtti(Graphics::TCustomCanvas)},
  {L"TCustomCategoryPanel", __delphirtti(Extctrls::TCustomCategoryPanel)},
//  {L"TCustomCategoryPanel.THeaderState", __delphirtti(Extctrls_tcustomcategorypanel::TCustomCategoryPanel.THeaderState)},
	{L"TCustomCategoryPanelGroup", __delphirtti(Extctrls::TCustomCategoryPanelGroup)},
//  {L"TCustomCategoryPanelGroup.THeaderStyle", __delphirtti(Extctrls_tcustomcategorypanelgroup::TCustomCategoryPanelGroup.THeaderStyle)},
  {L"TCustomCheckBox", __delphirtti(Stdctrls::TCustomCheckBox)},
	{L"TCustomColorBox", __delphirtti(Extctrls::TCustomColorBox)},
	{L"TCustomColorListBox", __delphirtti(Extctrls::TCustomColorListBox)},
//  {L"TCustomColors", __delphirtti(Dialogs::TCustomColors)},
  {L"TCustomCombo", __delphirtti(Stdctrls::TCustomCombo)},
  {L"TCustomComboBox", __delphirtti(Stdctrls::TCustomComboBox)},
  {L"TCustomComboBoxStrings", __delphirtti(Stdctrls::TCustomComboBoxStrings)},
  {L"TCustomComboBoxStringsClass", __delphirtti(Stdctrls::TCustomComboBoxStringsClass)},
  {L"TCustomControl", __delphirtti(Controls::TCustomControl)},
  {L"TCustomControlAction", __delphirtti(Controls::TCustomControlAction)},
  {L"TCustomControlBar", __delphirtti(Extctrls::TCustomControlBar)},
  {L"TCustomDockForm", __delphirtti(Forms::TCustomDockForm)},
  {L"TCustomDrawGrid", __delphirtti(Grids::TCustomDrawGrid)},
  {L"TCustomEdit", __delphirtti(Stdctrls::TCustomEdit)},
  {L"TCustomFileDialog", __delphirtti(Dialogs::TCustomFileDialog)},
  {L"TCustomFileOpenDialog", __delphirtti(Dialogs::TCustomFileOpenDialog)},
  {L"TCustomFileRun", __delphirtti(Extactns::TCustomFileRun)},
  {L"TCustomFileSaveDialog", __delphirtti(Dialogs::TCustomFileSaveDialog)},
  {L"TCustomFlowPanel", __delphirtti(Extctrls::TCustomFlowPanel)},
  {L"TCustomForm", __delphirtti(Forms::TCustomForm)},
  {L"TCustomFormClass", __delphirtti(Forms::TCustomFormClass)},
  {L"TCustomFrame", __delphirtti(Forms::TCustomFrame)},
  {L"TCustomFrameClass", __delphirtti(Forms::TCustomFrameClass)},
  {L"TCustomGestureCollection", __delphirtti(Controls::TCustomGestureCollection)},
  {L"TCustomGestureCollectionItem", __delphirtti(Controls::TCustomGestureCollectionItem)},
  {L"TCustomGestureEngine", __delphirtti(Controls::TCustomGestureEngine)},
//  {L"TCustomGestureEngine.TGestureEngineFlag", __delphirtti(Controls_tcustomgestureengine::TCustomGestureEngine.TGestureEngineFlag)},
//  {L"TCustomGestureEngine.TGestureEngineFlags", __delphirtti(Controls_tcustomgestureengine::TCustomGestureEngine.TGestureEngineFlags)},
  {L"TCustomGestureManager", __delphirtti(Controls::TCustomGestureManager)},
	{L"TCustomGrid", __delphirtti(Grids::TCustomGrid)},
  {L"TCustomGridPanel", __delphirtti(Extctrls::TCustomGridPanel)},
	{L"TCustomGroupBox", __delphirtti(Stdctrls::TCustomGroupBox)},
  {L"TCustomHint", __delphirtti(Controls::TCustomHint)},
  {L"TCustomHintShowHideThread", __delphirtti(Controls::TCustomHintShowHideThread)},
  {L"TCustomHintWindow", __delphirtti(Controls::TCustomHintWindow)},
  {L"TCustomImageList", __delphirtti(Imglist::TCustomImageList)},
  {L"TCustomIniFile", __delphirtti(Inifiles::TCustomIniFile)},
  {L"TCustomLabel", __delphirtti(Stdctrls::TCustomLabel)},
  {L"TCustomLabeledEdit", __delphirtti(Extctrls::TCustomLabeledEdit)},
  {L"TCustomLinkLabel", __delphirtti(Extctrls::TCustomLinkLabel)},
//  {L"TCustomLinkLabel.TLinkAlignment", __delphirtti(Extctrls_tcustomlinklabel::TCustomLinkLabel.TLinkAlignment)},
  {L"TCustomListAction", __delphirtti(Listactns::TCustomListAction)},
  {L"TCustomListBox", __delphirtti(Stdctrls::TCustomListBox)},
  {L"TCustomListControl", __delphirtti(Controls::TCustomListControl)},
  {L"TCustomMaskEdit", __delphirtti(Mask::TCustomMaskEdit)},
  {L"TCustomMemo", __delphirtti(Stdctrls::TCustomMemo)},
  {L"TCustomMemoryStream", __delphirtti(Classes::TCustomMemoryStream)},
  {L"TCustomMultiSelectListControl", __delphirtti(Controls::TCustomMultiSelectListControl)},
  {L"TCustomPanel", __delphirtti(Extctrls::TCustomPanel)},
  {L"TCustomPanningWindow", __delphirtti(Controls::TCustomPanningWindow)},
  {L"TCustomRadioGroup", __delphirtti(Extctrls::TCustomRadioGroup)},
  {L"TCustomStaticListAction", __delphirtti(Listactns::TCustomStaticListAction)},
  {L"TCustomStaticText", __delphirtti(Stdctrls::TCustomStaticText)},
  {L"TCustomTaskDialog", __delphirtti(Dialogs::TCustomTaskDialog)},
  {L"TCustomTouchManager", __delphirtti(Controls::TCustomTouchManager)},
  {L"TCustomTransparentControl", __delphirtti(Controls::TCustomTransparentControl)},
  {L"TCustomTrayIcon", __delphirtti(Extctrls::TCustomTrayIcon)},
	{L"TCustomVariantType", __delphirtti(Variants::TCustomVariantType)},
  {L"TCustomVariantTypeClass", __delphirtti(Variants::TCustomVariantTypeClass)},
  {L"TCustomVirtualListAction", __delphirtti(Listactns::TCustomVirtualListAction)},
	{L"TCustomZStream", __delphirtti(Zlib::TCustomZStream)},
  {L"TDLLProc", __delphirtti(System::TDLLProc)},
  {L"TDLLProcEx", __delphirtti(System::TDLLProcEx)},
  {L"TDataModule", __delphirtti(Classes::TDataModule)},
  {L"TDate", __delphirtti(System::TDate)},
  {L"TDateTime", __delphirtti(System::TDateTime)},
//  {L"TDateTimeInfoRec", __delphirtti(Sysutils::TDateTimeInfoRec)},
//  {L"TDayTable", __delphirtti(Sysutils::TDayTable)},
  {L"TDefaultGenericInterface", __delphirtti(Generics_defaults::TDefaultGenericInterface)},
  {L"TDefaultMonitor", __delphirtti(Forms::TDefaultMonitor)},
  {L"TDictionaryOwnerships", __delphirtti(Generics_collections::TDictionaryOwnerships)},
//	{L"TDirectory", __delphirtti(Ioutils::TDirectory)},
//  {L"TDirectory.TDirectoryWalkProc", __delphirtti(Ioutils_tdirectory::TDirectory.TDirectoryWalkProc)},
//  {L"TDirectory.TFilterPredicate", __delphirtti(Ioutils_tdirectory::TDirectory.TFilterPredicate)},
//  {L"TDispDesc", __delphirtti(System::TDispDesc)},
//  {L"TDispatchMessage", __delphirtti(System::TDispatchMessage)},
	{L"TDisplayOption", __delphirtti(Valedit::TDisplayOption)},
  {L"TDisplayOptions", __delphirtti(Valedit::TDisplayOptions)},
  {L"TDockCaptionDrawer", __delphirtti(Captioneddocktree::TDockCaptionDrawer)},
  {L"TDockCaptionDrawerClass", __delphirtti(Captioneddocktree::TDockCaptionDrawerClass)},
  {L"TDockCaptionOrientation", __delphirtti(Captioneddocktree::TDockCaptionOrientation)},
  {L"TDockCaptionPinButton", __delphirtti(Captioneddocktree::TDockCaptionPinButton)},
  {L"TDockClientInfo", __delphirtti(Docktabset::TDockClientInfo)},
  {L"TDockDropEvent", __delphirtti(Controls::TDockDropEvent)},
//  {L"TDockNotifyRec", __delphirtti(Controls::TDockNotifyRec)},
	{L"TDockOrientation", __delphirtti(Controls::TDockOrientation)},
  {L"TDockOverEvent", __delphirtti(Controls::TDockOverEvent)},
  {L"TDockTabSet", __delphirtti(Docktabset::TDockTabSet)},
  {L"TDockTree", __delphirtti(Controls::TDockTree)},
	{L"TDockTreeClass", __delphirtti(Controls::TDockTreeClass)},
  {L"TDockZone", __delphirtti(Controls::TDockZone)},
//  {L"TDoubleDynArray", __delphirtti(Types::TDoubleDynArray)},
  {L"TDownLoadURL", __delphirtti(Extactns::TDownLoadURL)},
  {L"TDownloadProgressEvent", __delphirtti(Extactns::TDownloadProgressEvent)},
  {L"TDragControlObject", __delphirtti(Controls::TDragControlObject)},
  {L"TDragControlObjectEx", __delphirtti(Controls::TDragControlObjectEx)},
  {L"TDragDockObject", __delphirtti(Controls::TDragDockObject)},
  {L"TDragDockObjectEx", __delphirtti(Controls::TDragDockObjectEx)},
  {L"TDragDropEvent", __delphirtti(Controls::TDragDropEvent)},
  {L"TDragImageList", __delphirtti(Controls::TDragImageList)},
  {L"TDragKind", __delphirtti(Controls::TDragKind)},
  {L"TDragMessage", __delphirtti(Controls::TDragMessage)},
  {L"TDragMode", __delphirtti(Controls::TDragMode)},
  {L"TDragObject", __delphirtti(Controls::TDragObject)},
  {L"TDragObjectClass", __delphirtti(Controls::TDragObjectClass)},
  {L"TDragObjectEx", __delphirtti(Controls::TDragObjectEx)},
  {L"TDragOverEvent", __delphirtti(Controls::TDragOverEvent)},
//  {L"TDragRec", __delphirtti(Controls::TDragRec)},
  {L"TDragState", __delphirtti(Controls::TDragState)},
  {L"TDrawCellEvent", __delphirtti(Grids::TDrawCellEvent)},
  {L"TDrawGrid", __delphirtti(Grids::TDrawGrid)},
  {L"TDrawItemEvent", __delphirtti(Stdctrls::TDrawItemEvent)},
  {L"TDrawingStyle", __delphirtti(Imglist::TDrawingStyle)},
	{L"TDuplicates", __delphirtti(Classes::TDuplicates)},
//  {L"TDynArrayTypeInfo", __delphirtti(System::TDynArrayTypeInfo)},
  {L"TEdgeBorder", __delphirtti(Toolwin::TEdgeBorder)},
  {L"TEdgeBorders", __delphirtti(Toolwin::TEdgeBorders)},
  {L"TEdgePart", __delphirtti(Tabs::TEdgePart)},
	{L"TEdgeStyle", __delphirtti(Toolwin::TEdgeStyle)},
  {L"TEdgeType", __delphirtti(Tabs::TEdgeType)},
  {L"TEdit", __delphirtti(Stdctrls::TEdit)},
  {L"TEditAction", __delphirtti(Stdactns::TEditAction)},
  {L"TEditButton", __delphirtti(Extctrls::TEditButton)},
//  {L"TEditButton.TButtonPosition", __delphirtti(Extctrls_teditbutton::TEditButton.TButtonPosition)},
//  {L"TEditButton.TButtonState", __delphirtti(Extctrls_teditbutton::TEditButton.TButtonState)},
//  {L"TEditButton.TGlyph", __delphirtti(Extctrls_teditbutton::TEditButton.TGlyph)},
  {L"TEditButtonClass", __delphirtti(Extctrls::TEditButtonClass)},
  {L"TEditCharCase", __delphirtti(Stdctrls::TEditCharCase)},
  {L"TEditCopy", __delphirtti(Stdactns::TEditCopy)},
  {L"TEditCut", __delphirtti(Stdactns::TEditCut)},
  {L"TEditDelete", __delphirtti(Stdactns::TEditDelete)},
  {L"TEditMask", __delphirtti(Maskutils::TEditMask)},
  {L"TEditPaste", __delphirtti(Stdactns::TEditPaste)},
  {L"TEditSelectAll", __delphirtti(Stdactns::TEditSelectAll)},
  {L"TEditStyle", __delphirtti(Grids::TEditStyle)},
  {L"TEditUndo", __delphirtti(Stdactns::TEditUndo)},
  {L"TEllipsisPosition", __delphirtti(Stdctrls::TEllipsisPosition)},
  {L"TEncodeType", __delphirtti(Widestrutils::TEncodeType)},
  {L"TEncoding", __delphirtti(Sysutils::TEncoding)},
  {L"TEndBandMoveEvent", __delphirtti(Extctrls::TEndBandMoveEvent)},
  {L"TEndDragEvent", __delphirtti(Controls::TEndDragEvent)},
	{L"TEnumActionProc", __delphirtti(Actnlist::TEnumActionProc)},
  {L"TEnumModuleFunc", __delphirtti(System::TEnumModuleFunc)},
  {L"TEnumModuleFuncLW", __delphirtti(System::TEnumModuleFuncLW)},
  {L"TEvent", __delphirtti(Syncobjs::TEvent)},
  {L"TExceptClsProc", __delphirtti(System::TExceptClsProc)},
  {L"TExceptObjProc", __delphirtti(System::TExceptObjProc)},
	{L"TExceptionEvent", __delphirtti(Forms::TExceptionEvent)},
//  {L"TExceptionRecord", __delphirtti(System::TExceptionRecord)},
  {L"TExpandStyle", __delphirtti(Extctrls::TExpandStyle)},
  {L"TFDApplyEvent", __delphirtti(Dialogs::TFDApplyEvent)},
  {L"TFNDrawText", __delphirtti(Stdctrls::TFNDrawText)},
  {L"TFPUException", __delphirtti(Math::TFPUException)},
  {L"TFPUExceptionMask", __delphirtti(Math::TFPUExceptionMask)},
  {L"TFPUPrecisionMode", __delphirtti(Math::TFPUPrecisionMode)},
  {L"TFPURoundingMode", __delphirtti(Math::TFPURoundingMode)},
  {L"TFavoriteLinkItem", __delphirtti(Dialogs::TFavoriteLinkItem)},
  {L"TFavoriteLinkItems", __delphirtti(Dialogs::TFavoriteLinkItems)},
  {L"TFavoriteLinkItemsEnumerator", __delphirtti(Dialogs::TFavoriteLinkItemsEnumerator)},
//  {L"TFile", __delphirtti(Ioutils::TFile)},
  {L"TFileAccess", __delphirtti(Ioutils::TFileAccess)},
  {L"TFileAction", __delphirtti(Stdactns::TFileAction)},
  {L"TFileAttribute", __delphirtti(Ioutils::TFileAttribute)},
  {L"TFileAttributes", __delphirtti(Ioutils::TFileAttributes)},
  {L"TFileDialogCloseEvent", __delphirtti(Dialogs::TFileDialogCloseEvent)},
  {L"TFileDialogFolderChangingEvent", __delphirtti(Dialogs::TFileDialogFolderChangingEvent)},
  {L"TFileDialogOption", __delphirtti(Dialogs::TFileDialogOption)},
  {L"TFileDialogOptions", __delphirtti(Dialogs::TFileDialogOptions)},
  {L"TFileDialogOverwriteEvent", __delphirtti(Dialogs::TFileDialogOverwriteEvent)},
	{L"TFileDialogOverwriteResponse", __delphirtti(Dialogs::TFileDialogOverwriteResponse)},
  {L"TFileDialogShareViolationEvent", __delphirtti(Dialogs::TFileDialogShareViolationEvent)},
  {L"TFileDialogShareViolationResponse", __delphirtti(Dialogs::TFileDialogShareViolationResponse)},
  {L"TFileEditStyle", __delphirtti(Dialogs::TFileEditStyle)},
  {L"TFileExit", __delphirtti(Stdactns::TFileExit)},
  {L"TFileIOFunc", __delphirtti(System::TFileIOFunc)},
  {L"TFileMode", __delphirtti(Ioutils::TFileMode)},
	{L"TFileName", __delphirtti(Sysutils::TFileName)},
  {L"TFileOpen", __delphirtti(Stdactns::TFileOpen)},
  {L"TFileOpenDialog", __delphirtti(Dialogs::TFileOpenDialog)},
  {L"TFileOpenWith", __delphirtti(Stdactns::TFileOpenWith)},
  {L"TFilePageSetup", __delphirtti(Stdactns::TFilePageSetup)},
  {L"TFilePrintSetup", __delphirtti(Stdactns::TFilePrintSetup)},
//  {L"TFileRec", __delphirtti(System::TFileRec)},
  {L"TFileRun", __delphirtti(Extactns::TFileRun)},
  {L"TFileSaveAs", __delphirtti(Stdactns::TFileSaveAs)},
  {L"TFileSaveDialog", __delphirtti(Dialogs::TFileSaveDialog)},
  {L"TFileShare", __delphirtti(Ioutils::TFileShare)},
  {L"TFileStream", __delphirtti(Classes::TFileStream)},
  {L"TFileTypeItem", __delphirtti(Dialogs::TFileTypeItem)},
  {L"TFileTypeItems", __delphirtti(Dialogs::TFileTypeItems)},
	{L"TFilenameCaseMatch", __delphirtti(Ansistrings::TFilenameCaseMatch)},
  {L"TFiler", __delphirtti(Classes::TFiler)},
  {L"TFilerFlag", __delphirtti(Classes::TFilerFlag)},
  {L"TFilerFlags", __delphirtti(Classes::TFilerFlags)},
  {L"TFillMode", __delphirtti(Graphics::TFillMode)},
  {L"TFillStyle", __delphirtti(Graphics::TFillStyle)},
  {L"TFindAncestorEvent", __delphirtti(Classes::TFindAncestorEvent)},
	{L"TFindComponentClassEvent", __delphirtti(Classes::TFindComponentClassEvent)},
  {L"TFindComponentInstanceEvent", __delphirtti(Classes::TFindComponentInstanceEvent)},
  {L"TFindDialog", __delphirtti(Dialogs::TFindDialog)},
  {L"TFindGlobalComponent", __delphirtti(Classes::TFindGlobalComponent)},
  {L"TFindItemKind", __delphirtti(Menus::TFindItemKind)},
  {L"TFindMethodEvent", __delphirtti(Classes::TFindMethodEvent)},
  {L"TFindMethodInstanceEvent", __delphirtti(Classes::TFindMethodInstanceEvent)},
  {L"TFindMethodNameEvent", __delphirtti(Classes::TFindMethodNameEvent)},
	{L"TFindOption", __delphirtti(Dialogs::TFindOption)},
  {L"TFindOptions", __delphirtti(Dialogs::TFindOptions)},
  {L"TFindReplaceFunc", __delphirtti(Dialogs::TFindReplaceFunc)},
  {L"TFixedCellClickEvent", __delphirtti(Grids::TFixedCellClickEvent)},
  {L"TFloatFormat", __delphirtti(Sysutils::TFloatFormat)},
//  {L"TFloatRec", __delphirtti(Sysutils::TFloatRec)},
  {L"TFloatValue", __delphirtti(Sysutils::TFloatValue)},
  {L"TFlowPanel", __delphirtti(Extctrls::TFlowPanel)},
  {L"TFlowStyle", __delphirtti(Extctrls::TFlowStyle)},
  {L"TFocusState", __delphirtti(Forms::TFocusState)},
  {L"TFont", __delphirtti(Graphics::TFont)},
  {L"TFontCharset", __delphirtti(Graphics::TFontCharset)},
//  {L"TFontData", __delphirtti(Graphics::TFontData)},
//  {L"TFontDataName", __delphirtti(Graphics::TFontDataName)},
  {L"TFontDialog", __delphirtti(Dialogs::TFontDialog)},
  {L"TFontDialogDevice", __delphirtti(Dialogs::TFontDialogDevice)},
  {L"TFontDialogOption", __delphirtti(Dialogs::TFontDialogOption)},
  {L"TFontDialogOptions", __delphirtti(Dialogs::TFontDialogOptions)},
  {L"TFontEdit", __delphirtti(Stdactns::TFontEdit)},
  {L"TFontName", __delphirtti(Graphics::TFontName)},
	{L"TFontPitch", __delphirtti(Graphics::TFontPitch)},
  {L"TFontQuality", __delphirtti(Graphics::TFontQuality)},
  {L"TFontRecall", __delphirtti(Graphics::TFontRecall)},
  {L"TFontStyle", __delphirtti(Graphics::TFontStyle)},
  {L"TFontStyles", __delphirtti(Graphics::TFontStyles)},
  {L"TFontStylesBase", __delphirtti(Graphics::TFontStylesBase)},
  {L"TForEachZoneProc", __delphirtti(Controls::TForEachZoneProc)},
  {L"TForm", __delphirtti(Forms::TForm)},
  {L"TFormBorderStyle", __delphirtti(Forms::TFormBorderStyle)},
	{L"TFormClass", __delphirtti(Forms::TFormClass)},
  {L"TFormState", __delphirtti(Forms::TFormState)},
  {L"TFormStyle", __delphirtti(Forms::TFormStyle)},
//  {L"TFormatSettings", __delphirtti(Sysutils::TFormatSettings)},
  {L"TFrame", __delphirtti(Forms::TFrame)},
//  {L"TGUID", __delphirtti(System::TGUID)},
  {L"TGestureArray", __delphirtti(Controls::TGestureArray)},
  {L"TGestureEvent", __delphirtti(Controls::TGestureEvent)},
//  {L"TGestureEventInfo", __delphirtti(Controls::TGestureEventInfo)},
  {L"TGestureID", __delphirtti(Controls::TGestureID)},
  {L"TGestureOption", __delphirtti(Controls::TGestureOption)},
  {L"TGestureOptions", __delphirtti(Controls::TGestureOptions)},
  {L"TGesturePointArray", __delphirtti(Controls::TGesturePointArray)},
  {L"TGestureType", __delphirtti(Controls::TGestureType)},
  {L"TGestureTypes", __delphirtti(Controls::TGestureTypes)},
  {L"TGetChildProc", __delphirtti(Classes::TGetChildProc)},
  {L"TGetClass", __delphirtti(Classes::TGetClass)},
  {L"TGetColorsEvent", __delphirtti(Extctrls::TGetColorsEvent)},
  {L"TGetEditEvent", __delphirtti(Grids::TGetEditEvent)},
	{L"TGetExtentsFunc", __delphirtti(Grids::TGetExtentsFunc)},
  {L"TGetHandleEvent", __delphirtti(Forms::TGetHandleEvent)},
  {L"TGetItemCountEvent", __delphirtti(Listactns::TGetItemCountEvent)},
  {L"TGetItemEvent", __delphirtti(Listactns::TGetItemEvent)},
  {L"TGetLookupInfoEvent", __delphirtti(Classes::TGetLookupInfoEvent)},
  {L"TGetModuleProc", __delphirtti(Classes::TGetModuleProc)},
  {L"TGetPickListEvent", __delphirtti(Valedit::TGetPickListEvent)},
  {L"TGetSiteInfoEvent", __delphirtti(Controls::TGetSiteInfoEvent)},
  {L"TGetStrProc", __delphirtti(Classes::TGetStrProc)},
  {L"TGetVirtualItemEvent", __delphirtti(Listactns::TGetVirtualItemEvent)},
	{L"TGlassFrame", __delphirtti(Forms::TGlassFrame)},
  {L"TGradientDirection", __delphirtti(Graphutil::TGradientDirection)},
  {L"TGraphic", __delphirtti(Graphics::TGraphic)},
  {L"TGraphicClass", __delphirtti(Graphics::TGraphicClass)},
  {L"TGraphicControl", __delphirtti(Controls::TGraphicControl)},
  {L"TGraphicsObject", __delphirtti(Graphics::TGraphicsObject)},
//  {L"TGridAxisDrawInfo", __delphirtti(Grids::TGridAxisDrawInfo)},
//  {L"TGridCoord", __delphirtti(Grids::TGridCoord)},
//  {L"TGridDrawInfo", __delphirtti(Grids::TGridDrawInfo)},
  {L"TGridDrawState", __delphirtti(Grids::TGridDrawState)},
  {L"TGridDrawingStyle", __delphirtti(Grids::TGridDrawingStyle)},
  {L"TGridMovement", __delphirtti(Grids::TGridMovement)},
  {L"TGridOption", __delphirtti(Grids::TGridOption)},
  {L"TGridOptions", __delphirtti(Grids::TGridOptions)},
  {L"TGridPanel", __delphirtti(Extctrls::TGridPanel)},
//  {L"TGridRect", __delphirtti(Grids::TGridRect)},
  {L"TGridScrollDirection", __delphirtti(Grids::TGridScrollDirection)},
  {L"TGridState", __delphirtti(Grids::TGridState)},
	{L"TGroupBox", __delphirtti(Stdctrls::TGroupBox)},
  {L"TGrpButtonDrawEvent", __delphirtti(Buttongroup::TGrpButtonDrawEvent)},
  {L"TGrpButtonDrawIconEvent", __delphirtti(Buttongroup::TGrpButtonDrawIconEvent)},
  {L"TGrpButtonEvent", __delphirtti(Buttongroup::TGrpButtonEvent)},
  {L"TGrpButtonItem", __delphirtti(Buttongroup::TGrpButtonItem)},
  {L"TGrpButtonItemClass", __delphirtti(Buttongroup::TGrpButtonItemClass)},
  {L"TGrpButtonItems", __delphirtti(Buttongroup::TGrpButtonItems)},
  {L"TGrpButtonItemsClass", __delphirtti(Buttongroup::TGrpButtonItemsClass)},
  {L"TGrpButtonOptions", __delphirtti(Buttongroup::TGrpButtonOptions)},
  {L"TGrpButtonReorderEvent", __delphirtti(Buttongroup::TGrpButtonReorderEvent)},
  {L"TGuidHelper", __delphirtti(Sysutils::TGuidHelper)},
	{L"THandleObject", __delphirtti(Syncobjs::THandleObject)},
  {L"THandleObjectArray", __delphirtti(Syncobjs::THandleObjectArray)},
  {L"THandleStream", __delphirtti(Classes::THandleStream)},
//  {L"THashItem", __delphirtti(Inifiles::THashItem)},
  {L"THashedStringList", __delphirtti(Inifiles::THashedStringList)},
  {L"THeader", __delphirtti(Extctrls::THeader)},
//  {L"THeapStatus", __delphirtti(System::THeapStatus)},
  {L"THelpAction", __delphirtti(Stdactns::THelpAction)},
  {L"THelpContents", __delphirtti(Stdactns::THelpContents)},
  {L"THelpContext", __delphirtti(Classes::THelpContext)},
  {L"THelpContextAction", __delphirtti(Stdactns::THelpContextAction)},
  {L"THelpEvent", __delphirtti(Forms::THelpEvent)},
  {L"THelpOnHelp", __delphirtti(Stdactns::THelpOnHelp)},
  {L"THelpTopicSearch", __delphirtti(Stdactns::THelpTopicSearch)},
  {L"THelpType", __delphirtti(Classes::THelpType)},
  {L"THintAction", __delphirtti(Stdactns::THintAction)},
  {L"THintEvent", __delphirtti(Actnlist::THintEvent)},
//  {L"THintInfo", __delphirtti(Controls::THintInfo)},
  {L"THintWindow", __delphirtti(Controls::THintWindow)},
  {L"THintWindowClass", __delphirtti(Controls::THintWindowClass)},
//  {L"THotTrackCellInfo", __delphirtti(Grids::THotTrackCellInfo)},
  {L"TIcon", __delphirtti(Graphics::TIcon)},
  {L"TIconImage", __delphirtti(Graphics::TIconImage)},
//  {L"TIconRec", __delphirtti(Graphics::TIconRec)},
//  {L"TIdentMapEntry", __delphirtti(Classes::TIdentMapEntry)},
  {L"TIdentToInt", __delphirtti(Classes::TIdentToInt)},
  {L"TIdleEvent", __delphirtti(Forms::TIdleEvent)},
  {L"TImage", __delphirtti(Extctrls::TImage)},
  {L"TImageAlignment", __delphirtti(Stdctrls::TImageAlignment)},
	{L"TImageIndex", __delphirtti(Imglist::TImageIndex)},
  {L"TImageList", __delphirtti(Controls::TImageList)},
  {L"TImageMargins", __delphirtti(Stdctrls::TImageMargins)},
//  {L"TImageThunkData", __delphirtti(System::TImageThunkData)},
  {L"TImageType", __delphirtti(Imglist::TImageType)},
  {L"TImeMode", __delphirtti(Controls::TImeMode)},
  {L"TImeName", __delphirtti(Controls::TImeName)},
  {L"TIncludeItemEvent", __delphirtti(Dialogs::TIncludeItemEvent)},
  {L"TIniFile", __delphirtti(Inifiles::TIniFile)},
//  {L"TInitContext", __delphirtti(System::TInitContext)},
  {L"TInplaceEdit", __delphirtti(Grids::TInplaceEdit)},
  {L"TInplaceEditList", __delphirtti(Grids::TInplaceEditList)},
//  {L"TInt64DynArray", __delphirtti(Types::TInt64DynArray)},
  {L"TIntToIdent", __delphirtti(Classes::TIntToIdent)},
  {L"TIntegerBucketList", __delphirtti(Contnrs::TIntegerBucketList)},
	{L"TIntegerDynArray", __delphirtti(System::TIntegerDynArray)},
	{L"TInteractiveGesture", __delphirtti(Controls::TInteractiveGesture)},
  {L"TInteractiveGestureFlag", __delphirtti(Controls::TInteractiveGestureFlag)},
  {L"TInteractiveGestureFlags", __delphirtti(Controls::TInteractiveGestureFlags)},
  {L"TInteractiveGestureOption", __delphirtti(Controls::TInteractiveGestureOption)},
  {L"TInteractiveGestureOptions", __delphirtti(Controls::TInteractiveGestureOptions)},
  {L"TInteractiveGestures", __delphirtti(Controls::TInteractiveGestures)},
//  {L"TInterfaceEntry", __delphirtti(System::TInterfaceEntry)},
  {L"TInterfaceList", __delphirtti(Classes::TInterfaceList)},
  {L"TInterfaceListEnumerator", __delphirtti(Classes::TInterfaceListEnumerator)},
//  {L"TInterfaceTable", __delphirtti(System::TInterfaceTable)},
  {L"TInterfacedClass", __delphirtti(System::TInterfacedClass)},
  {L"TInterfacedObject", __delphirtti(System::TInterfacedObject)},
  {L"TInterfacedPersistent", __delphirtti(Classes::TInterfacedPersistent)},
	{L"TInterlocked", __delphirtti(Syncobjs::TInterlocked)},
  {L"TInvokeableVariantType", __delphirtti(Variants::TInvokeableVariantType)},
  {L"TIsUniqueGlobalComponentName", __delphirtti(Classes::TIsUniqueGlobalComponentName)},
  {L"TItemCollection", __delphirtti(Categorybuttons::TItemCollection)},
  {L"TItemProp", __delphirtti(Valedit::TItemProp)},
  {L"TItemProps", __delphirtti(Valedit::TItemProps)},
  {L"TItemSelectedEvent", __delphirtti(Listactns::TItemSelectedEvent)},
  {L"TKeyEvent", __delphirtti(Controls::TKeyEvent)},
  {L"TKeyOption", __delphirtti(Valedit::TKeyOption)},
  {L"TKeyOptions", __delphirtti(Valedit::TKeyOptions)},
  {L"TKeyPressEvent", __delphirtti(Controls::TKeyPressEvent)},
  {L"TLBFindDataEvent", __delphirtti(Stdctrls::TLBFindDataEvent)},
  {L"TLBGetColorsEvent", __delphirtti(Extctrls::TLBGetColorsEvent)},
  {L"TLBGetDataEvent", __delphirtti(Stdctrls::TLBGetDataEvent)},
  {L"TLBGetDataObjectEvent", __delphirtti(Stdctrls::TLBGetDataObjectEvent)},
	{L"TLabel", __delphirtti(Stdctrls::TLabel)},
  {L"TLabelPosition", __delphirtti(Extctrls::TLabelPosition)},
  {L"TLabeledEdit", __delphirtti(Extctrls::TLabeledEdit)},
//  {L"TLangRec", __delphirtti(Sysutils::TLangRec)},
  {L"TLanguages", __delphirtti(Sysutils::TLanguages)},
  {L"TLeftRight", __delphirtti(Classes::TLeftRight)},
//  {L"TLibModule", __delphirtti(System::TLibModule)},
  {L"TLightweightEvent", __delphirtti(Syncobjs::TLightweightEvent)},
  {L"TLightweightSemaphore", __delphirtti(Syncobjs::TLightweightSemaphore)},
  {L"TLinkLabel", __delphirtti(Extctrls::TLinkLabel)},
  {L"TList", __delphirtti(Classes::TList)},
//  {L"TList.TDirection", __delphirtti(Classes_tlist::TList.TDirection)},
  {L"TListActionLink", __delphirtti(Listactns::TListActionLink)},
  {L"TListAssignOp", __delphirtti(Classes::TListAssignOp)},
	{L"TListBox", __delphirtti(Stdctrls::TListBox)},
  {L"TListBoxStyle", __delphirtti(Stdctrls::TListBoxStyle)},
  {L"TListCompareEvent", __delphirtti(Listactns::TListCompareEvent)},
  {L"TListControlAction", __delphirtti(Extactns::TListControlAction)},
  {L"TListControlClearSelection", __delphirtti(Extactns::TListControlClearSelection)},
  {L"TListControlCopySelection", __delphirtti(Extactns::TListControlCopySelection)},
  {L"TListControlDeleteSelection", __delphirtti(Extactns::TListControlDeleteSelection)},
  {L"TListControlItem", __delphirtti(Listactns::TListControlItem)},
  {L"TListControlItemClass", __delphirtti(Listactns::TListControlItemClass)},
  {L"TListControlItems", __delphirtti(Listactns::TListControlItems)},
  {L"TListControlMoveSelection", __delphirtti(Extactns::TListControlMoveSelection)},
  {L"TListControlSelectAll", __delphirtti(Extactns::TListControlSelectAll)},
  {L"TListEnumerator", __delphirtti(Classes::TListEnumerator)},
  {L"TListItemsCompare", __delphirtti(Listactns::TListItemsCompare)},
	{L"TListItemsSortType", __delphirtti(Listactns::TListItemsSortType)},
  {L"TListNotification", __delphirtti(Classes::TListNotification)},
  {L"TListSortCompare", __delphirtti(Classes::TListSortCompare)},
//  {L"TListSortCompareFunc", __delphirtti(Classes::TListSortCompareFunc)},
  {L"TLoadResource", __delphirtti(Imglist::TLoadResource)},
  {L"TLoadResources", __delphirtti(Imglist::TLoadResources)},
  {L"TLocalTimeType", __delphirtti(Dateutils::TLocalTimeType)},
  {L"TLocaleOptions", __delphirtti(Sysutils::TLocaleOptions)},
	{L"TLongWordDynArray", __delphirtti(System::TLongWordDynArray)},
  {L"TMBCSEncoding", __delphirtti(Sysutils::TMBCSEncoding)},
  {L"TMailSendStatus", __delphirtti(Extactns::TMailSendStatus)},
  {L"TMailSendStatusEvent", __delphirtti(Extactns::TMailSendStatusEvent)},
  {L"TMainMenu", __delphirtti(Menus::TMainMenu)},
  {L"TMarginSize", __delphirtti(Controls::TMarginSize)},
  {L"TMargins", __delphirtti(Controls::TMargins)},
	{L"TMask", __delphirtti(Masks::TMask)},
  {L"TMaskCharType", __delphirtti(Maskutils::TMaskCharType)},
  {L"TMaskDirectives", __delphirtti(Maskutils::TMaskDirectives)},
  {L"TMaskEdit", __delphirtti(Mask::TMaskEdit)},
  {L"TMaskedState", __delphirtti(Mask::TMaskedState)},
  {L"TMaskedText", __delphirtti(Maskutils::TMaskedText)},
  {L"TMbcsByteType", __delphirtti(Sysutils::TMbcsByteType)},
  {L"TMeasureItemEvent", __delphirtti(Stdctrls::TMeasureItemEvent)},
  {L"TMeasureTabEvent", __delphirtti(Tabs::TMeasureTabEvent)},
  {L"TMemIniFile", __delphirtti(Inifiles::TMemIniFile)},
  {L"TMemo", __delphirtti(Stdctrls::TMemo)},
//  {L"TMemoryManager", __delphirtti(System::TMemoryManager)},
//  {L"TMemoryManagerEx", __delphirtti(System::TMemoryManagerEx)},
//	{L"TMemoryManagerState", __delphirtti(System::TMemoryManagerState)},
//  {L"TMemoryMap", __delphirtti(System::TMemoryMap)},
  {L"TMemoryStream", __delphirtti(Classes::TMemoryStream)},
  {L"TMenu", __delphirtti(Menus::TMenu)},
  {L"TMenuActionLink", __delphirtti(Menus::TMenuActionLink)},
  {L"TMenuActionLinkClass", __delphirtti(Menus::TMenuActionLinkClass)},
  {L"TMenuAnimation", __delphirtti(Menus::TMenuAnimation)},
  {L"TMenuAnimations", __delphirtti(Menus::TMenuAnimations)},
  {L"TMenuAutoFlag", __delphirtti(Menus::TMenuAutoFlag)},
  {L"TMenuBreak", __delphirtti(Menus::TMenuBreak)},
  {L"TMenuChangeEvent", __delphirtti(Menus::TMenuChangeEvent)},
  {L"TMenuDrawItemEvent", __delphirtti(Menus::TMenuDrawItemEvent)},
  {L"TMenuItem", __delphirtti(Menus::TMenuItem)},
  {L"TMenuItemAutoFlag", __delphirtti(Menus::TMenuItemAutoFlag)},
  {L"TMenuItemEnumerator", __delphirtti(Menus::TMenuItemEnumerator)},
  {L"TMenuItemStack", __delphirtti(Menus::TMenuItemStack)},
	{L"TMenuMeasureItemEvent", __delphirtti(Menus::TMenuMeasureItemEvent)},
//  {L"TMessage", __delphirtti(Messages::TMessage)},
  {L"TMessageEvent", __delphirtti(Forms::TMessageEvent)},
  {L"TMetafile", __delphirtti(Graphics::TMetafile)},
  {L"TMetafileCanvas", __delphirtti(Graphics::TMetafileCanvas)},
  {L"TMetafileImage", __delphirtti(Graphics::TMetafileImage)},
//  {L"TMethod", __delphirtti(System::TMethod)},
//  {L"TMethodImplementation.PFirstStageIntercept", __delphirtti(Rtti_tmethodimplementation::TMethodImplementation.PFirstStageIntercept)},
//	{L"TMethodImplementation.PInterceptFrame", __delphirtti(Rtti_tmethodimplementation::TMethodImplementation.PInterceptFrame)},
//	{L"TMethodImplementation.PParamLoc", __delphirtti(Rtti_tmethodimplementation::TMethodImplementation.PParamLoc)},
//  {L"TMethodImplementation.TFirstStageIntercept", __delphirtti(Rtti_tmethodimplementation::TMethodImplementation.TFirstStageIntercept)},
//  {L"TMethodImplementation.TFloatReg", __delphirtti(Rtti_tmethodimplementation::TMethodImplementation.TFloatReg)},
//	{L"TMethodImplementation.TInterceptFrame", __delphirtti(Rtti_tmethodimplementation::TMethodImplementation.TInterceptFrame)},
//  {L"TMethodImplementation.TInvokeInfo", __delphirtti(Rtti_tmethodimplementation::TMethodImplementation.TInvokeInfo)},
//  {L"TMethodImplementation.TParamLoc", __delphirtti(Rtti_tmethodimplementation::TMethodImplementation.TParamLoc)},
	{L"TMinimumBlockAlignment", __delphirtti(System::TMinimumBlockAlignment)},
  {L"TModalResult", __delphirtti(Controls::TModalResult)},
  {L"TModuleUnloadProc", __delphirtti(System::TModuleUnloadProc)},
  {L"TModuleUnloadProcLW", __delphirtti(System::TModuleUnloadProcLW)},
//  {L"TModuleUnloadRec", __delphirtti(System::TModuleUnloadRec)},
//	{L"TMonitor", __delphirtti(System::TMonitor)},
//  {L"TMonitor.PWaitingThread", __delphirtti(System_tmonitor::TMonitor.PWaitingThread)},
//  {L"TMonitor.TSpinLock", __delphirtti(System_tmonitor::TMonitor.TSpinLock)},
//  {L"TMonitor.TSpinWait", __delphirtti(System_tmonitor::TMonitor.TSpinWait)},
//  {L"TMonitor.TWaitingThread", __delphirtti(System_tmonitor::TMonitor.TWaitingThread)},
  {L"TMonitorDefaultTo", __delphirtti(Forms::TMonitorDefaultTo)},
//  {L"TMonitorSupport", __delphirtti(System::TMonitorSupport)},
  {L"TMouse", __delphirtti(Controls::TMouse)},
  {L"TMouseActivate", __delphirtti(Controls::TMouseActivate)},
	{L"TMouseActivateEvent", __delphirtti(Controls::TMouseActivateEvent)},
//  {L"TMouseActivateRec", __delphirtti(Controls::TMouseActivateRec)},
  {L"TMouseButton", __delphirtti(Controls::TMouseButton)},
  {L"TMouseEvent", __delphirtti(Controls::TMouseEvent)},
  {L"TMouseMoveEvent", __delphirtti(Controls::TMouseMoveEvent)},
  {L"TMouseWheelEvent", __delphirtti(Controls::TMouseWheelEvent)},
  {L"TMouseWheelUpDownEvent", __delphirtti(Controls::TMouseWheelUpDownEvent)},
  {L"TMovedEvent", __delphirtti(Grids::TMovedEvent)},
  {L"TMsgDlgBtn", __delphirtti(Dialogs::TMsgDlgBtn)},
  {L"TMsgDlgButtons", __delphirtti(Dialogs::TMsgDlgButtons)},
  {L"TMsgDlgType", __delphirtti(Dialogs::TMsgDlgType)},
	{L"TMultiReadExclusiveWriteSynchronizer", __delphirtti(Sysutils::TMultiReadExclusiveWriteSynchronizer)},
  {L"TMutex", __delphirtti(Syncobjs::TMutex)},
  {L"TNameType", __delphirtti(Sysutils::TNameType)},
  {L"TNextTab", __delphirtti(Extactns::TNextTab)},
  {L"TNotebook", __delphirtti(Extctrls::TNotebook)},
  {L"TNotifyEvent", __delphirtti(Classes::TNotifyEvent)},
  {L"TNullCompareRule", __delphirtti(Variants::TNullCompareRule)},
  {L"TNumGlyphs", __delphirtti(Buttons::TNumGlyphs)},
//  {L"TOFNotifyEx", __delphirtti(Dialogs::TOFNotifyEx)},
  {L"TObject", __delphirtti(System::TObject)},
  {L"TObjectBucketList", __delphirtti(Contnrs::TObjectBucketList)},
  {L"TObjectList", __delphirtti(Contnrs::TObjectList)},
  {L"TObjectQueue", __delphirtti(Contnrs::TObjectQueue)},
  {L"TObjectStack", __delphirtti(Contnrs::TObjectStack)},
  {L"TOnGetPickListItems", __delphirtti(Grids::TOnGetPickListItems)},
  {L"TOnValidateEvent", __delphirtti(Valedit::TOnValidateEvent)},
  {L"TOpenDialog", __delphirtti(Dialogs::TOpenDialog)},
  {L"TOpenOption", __delphirtti(Dialogs::TOpenOption)},
	{L"TOpenOptionEx", __delphirtti(Dialogs::TOpenOptionEx)},
  {L"TOpenOptions", __delphirtti(Dialogs::TOpenOptions)},
  {L"TOpenOptionsEx", __delphirtti(Dialogs::TOpenOptionsEx)},
  {L"TOpenPicture", __delphirtti(Extactns::TOpenPicture)},
  {L"TOpenPictureDialog", __delphirtti(Extdlgs::TOpenPictureDialog)},
  {L"TOpenTextFileDialog", __delphirtti(Extdlgs::TOpenTextFileDialog)},
  {L"TOperation", __delphirtti(Classes::TOperation)},
  {L"TOrderedList", __delphirtti(Contnrs::TOrderedList)},
  {L"TOverlay", __delphirtti(Imglist::TOverlay)},
  {L"TOwnedCollection", __delphirtti(Classes::TOwnedCollection)},
	{L"TPCharArray", __delphirtti(System::TPCharArray)},
  {L"TPackageInfoProc", __delphirtti(Sysutils::TPackageInfoProc)},
//  {L"TPackageTypeInfo", __delphirtti(System::TPackageTypeInfo)},
  {L"TPadding", __delphirtti(Controls::TPadding)},
  {L"TPage", __delphirtti(Extctrls::TPage)},
  {L"TPageMeasureUnits", __delphirtti(Dialogs::TPageMeasureUnits)},
  {L"TPageSetupBeforePaintEvent", __delphirtti(Dialogs::TPageSetupBeforePaintEvent)},
  {L"TPageSetupDialog", __delphirtti(Dialogs::TPageSetupDialog)},
  {L"TPageSetupDialogOption", __delphirtti(Dialogs::TPageSetupDialogOption)},
  {L"TPageSetupDialogOptions", __delphirtti(Dialogs::TPageSetupDialogOptions)},
  {L"TPageType", __delphirtti(Dialogs::TPageType)},
  {L"TPaintBox", __delphirtti(Extctrls::TPaintBox)},
  {L"TPaintPageEvent", __delphirtti(Dialogs::TPaintPageEvent)},
	{L"TPanDirection", __delphirtti(Imouse::TPanDirection)},
  {L"TPanDirections", __delphirtti(Imouse::TPanDirections)},
  {L"TPanOption", __delphirtti(Imouse::TPanOption)},
  {L"TPanOptions", __delphirtti(Imouse::TPanOptions)},
  {L"TPanel", __delphirtti(Extctrls::TPanel)},
  {L"TPanningWindow", __delphirtti(Imouse::TPanningWindow)},
	{L"TPanningWindowClass", __delphirtti(Controls::TPanningWindowClass)},
//  {L"TParentFormState", __delphirtti(Captioneddocktree::TParentFormState)},
  {L"TParser", __delphirtti(Classes::TParser)},
//  {L"TParser.TCharType", __delphirtti(Classes_tparser::TParser.TCharType)},
  {L"TParserErrorEvent", __delphirtti(Classes::TParserErrorEvent)},
//  {L"TPath", __delphirtti(Ioutils::TPath)},
  {L"TPathPrefixType", __delphirtti(Ioutils::TPathPrefixType)},
  {L"TPaymentTime", __delphirtti(Math::TPaymentTime)},
  {L"TPen", __delphirtti(Graphics::TPen)},
//	{L"TPenData", __delphirtti(Graphics::TPenData)},
  {L"TPenMode", __delphirtti(Graphics::TPenMode)},
  {L"TPenRecall", __delphirtti(Graphics::TPenRecall)},
  {L"TPenStyle", __delphirtti(Graphics::TPenStyle)},
  {L"TPersistent", __delphirtti(Classes::TPersistent)},
  {L"TPersistentClass", __delphirtti(Classes::TPersistentClass)},
  {L"TPicture", __delphirtti(Graphics::TPicture)},
  {L"TPixelFormat", __delphirtti(Graphics::TPixelFormat)},
//  {L"TPoint", __delphirtti(Types::TPoint)},
//  {L"TPointerList", __delphirtti(Classes::TPointerList)},
  {L"TPopupAlignment", __delphirtti(Menus::TPopupAlignment)},
//  {L"TPopupForm", __delphirtti(Forms::TPopupForm)},
  {L"TPopupFormArray", __delphirtti(Forms::TPopupFormArray)},
//  {L"TPopupFormInfo", __delphirtti(Controls::TPopupFormInfo)},
  {L"TPopupList", __delphirtti(Menus::TPopupList)},
  {L"TPopupMenu", __delphirtti(Menus::TPopupMenu)},
  {L"TPopupMode", __delphirtti(Forms::TPopupMode)},
//  {L"TPopupWnd", __delphirtti(Forms::TPopupWnd)},
  {L"TPopupWndArray", __delphirtti(Forms::TPopupWndArray)},
  {L"TPosition", __delphirtti(Forms::TPosition)},
	{L"TPreviousTab", __delphirtti(Extactns::TPreviousTab)},
  {L"TPrintDialog", __delphirtti(Dialogs::TPrintDialog)},
  {L"TPrintDialogOption", __delphirtti(Dialogs::TPrintDialogOption)},
  {L"TPrintDialogOptions", __delphirtti(Dialogs::TPrintDialogOptions)},
  {L"TPrintDlg", __delphirtti(Stdactns::TPrintDlg)},
  {L"TPrintRange", __delphirtti(Dialogs::TPrintRange)},
  {L"TPrintScale", __delphirtti(Forms::TPrintScale)},
  {L"TPrinter", __delphirtti(Printers::TPrinter)},
	{L"TPrinterCapabilities", __delphirtti(Printers::TPrinterCapabilities)},
  {L"TPrinterCapability", __delphirtti(Printers::TPrinterCapability)},
  {L"TPrinterKind", __delphirtti(Dialogs::TPrinterKind)},
  {L"TPrinterOrientation", __delphirtti(Printers::TPrinterOrientation)},
  {L"TPrinterSetupDialog", __delphirtti(Dialogs::TPrinterSetupDialog)},
  {L"TPrinterState", __delphirtti(Printers::TPrinterState)},
//  {L"TProc", __delphirtti(Sysutils::TProc)},
  {L"TProcedure", __delphirtti(Sysutils::TProcedure)},
  {L"TProgressEvent", __delphirtti(Graphics::TProgressEvent)},
  {L"TProgressStage", __delphirtti(Graphics::TProgressStage)},
  {L"TPushButtonActionLink", __delphirtti(Stdctrls::TPushButtonActionLink)},
  {L"TPushButtonActionLinkClass", __delphirtti(Stdctrls::TPushButtonActionLinkClass)},
  {L"TQueue", __delphirtti(Contnrs::TQueue)},
  {L"TRadioButton", __delphirtti(Stdctrls::TRadioButton)},
  {L"TRadioGroup", __delphirtti(Extctrls::TRadioGroup)},
  {L"TRaiseExceptObjProc", __delphirtti(System::TRaiseExceptObjProc)},
  {L"TRaiseExceptionProc", __delphirtti(System::TRaiseExceptionProc)},
  {L"TReadComponentsProc", __delphirtti(Classes::TReadComponentsProc)},
  {L"TReader", __delphirtti(Classes::TReader)},
  {L"TReaderError", __delphirtti(Classes::TReaderError)},
  {L"TReaderProc", __delphirtti(Classes::TReaderProc)},
	{L"TRecall", __delphirtti(Classes::TRecall)},
  {L"TRecipientCollection", __delphirtti(Extactns::TRecipientCollection)},
  {L"TRecipientItem", __delphirtti(Extactns::TRecipientItem)},
  {L"TRecipientType", __delphirtti(Extactns::TRecipientType)},
//  {L"TRect", __delphirtti(Types::TRect)},
  {L"TReferenceNameEvent", __delphirtti(Classes::TReferenceNameEvent)},
//  {L"TRegDataInfo", __delphirtti(Registry::TRegDataInfo)},
  {L"TRegDataType", __delphirtti(Registry::TRegDataType)},
  {L"TRegIniFile", __delphirtti(Registry::TRegIniFile)},
//  {L"TRegKeyInfo", __delphirtti(Registry::TRegKeyInfo)},
  {L"TRegistry", __delphirtti(Registry::TRegistry)},
  {L"TRegistryIniFile", __delphirtti(Registry::TRegistryIniFile)},
  {L"TReplaceDialog", __delphirtti(Dialogs::TReplaceDialog)},
  {L"TReplaceFlags", __delphirtti(Sysutils::TReplaceFlags)},
//  {L"TResData", __delphirtti(Graphics::TResData)},
//  {L"TResStringRec", __delphirtti(System::TResStringRec)},
  {L"TResType", __delphirtti(Imglist::TResType)},
  {L"TResizeStyle", __delphirtti(Extctrls::TResizeStyle)},
//  {L"TResource", __delphirtti(Graphics::TResource)},
  {L"TResourceStream", __delphirtti(Classes::TResourceStream)},
  {L"TRichEditAction", __delphirtti(Extactns::TRichEditAction)},
  {L"TRichEditAlignCenter", __delphirtti(Extactns::TRichEditAlignCenter)},
  {L"TRichEditAlignLeft", __delphirtti(Extactns::TRichEditAlignLeft)},
  {L"TRichEditAlignRight", __delphirtti(Extactns::TRichEditAlignRight)},
  {L"TRichEditBold", __delphirtti(Extactns::TRichEditBold)},
  {L"TRichEditBullets", __delphirtti(Extactns::TRichEditBullets)},
  {L"TRichEditItalic", __delphirtti(Extactns::TRichEditItalic)},
  {L"TRichEditStrikeOut", __delphirtti(Extactns::TRichEditStrikeOut)},
  {L"TRichEditUnderline", __delphirtti(Extactns::TRichEditUnderline)},
	{L"TRoundToEXRangeExtended", __delphirtti(Math::TRoundToEXRangeExtended)},
  {L"TRoundToRange", __delphirtti(Math::TRoundToRange)},
  {L"TRowCollection", __delphirtti(Extctrls::TRowCollection)},
  {L"TRowItem", __delphirtti(Extctrls::TRowItem)},
  {L"TRowSize", __delphirtti(Extctrls::TRowSize)},
//  {L"TRuntimeError", __delphirtti(System::TRuntimeError)},
  {L"TSafeCallErrorProc", __delphirtti(System::TSafeCallErrorProc)},
  {L"TSaveDialog", __delphirtti(Dialogs::TSaveDialog)},
  {L"TSavePicture", __delphirtti(Extactns::TSavePicture)},
  {L"TSavePictureDialog", __delphirtti(Extdlgs::TSavePictureDialog)},
  {L"TSaveTextFileDialog", __delphirtti(Extdlgs::TSaveTextFileDialog)},
  {L"TScalingFlags", __delphirtti(Controls::TScalingFlags)},
  {L"TScreen", __delphirtti(Forms::TScreen)},
  {L"TScrollBar", __delphirtti(Stdctrls::TScrollBar)},
  {L"TScrollBarInc", __delphirtti(Forms::TScrollBarInc)},
  {L"TScrollBarKind", __delphirtti(Forms::TScrollBarKind)},
  {L"TScrollBarStyle", __delphirtti(Forms::TScrollBarStyle)},
  {L"TScrollBox", __delphirtti(Forms::TScrollBox)},
  {L"TScrollBtn", __delphirtti(Tabs::TScrollBtn)},
  {L"TScrollCode", __delphirtti(Stdctrls::TScrollCode)},
  {L"TScrollDirection", __delphirtti(Graphutil::TScrollDirection)},
  {L"TScrollEvent", __delphirtti(Stdctrls::TScrollEvent)},
  {L"TScrollOrientation", __delphirtti(Tabs::TScrollOrientation)},
  {L"TScrollStyle", __delphirtti(Stdctrls::TScrollStyle)},
  {L"TScroller", __delphirtti(Tabs::TScroller)},
  {L"TScrollingWinControl", __delphirtti(Forms::TScrollingWinControl)},
  {L"TSearchAction", __delphirtti(Stdactns::TSearchAction)},
  {L"TSearchFind", __delphirtti(Stdactns::TSearchFind)},
  {L"TSearchFindFirst", __delphirtti(Stdactns::TSearchFindFirst)},
	{L"TSearchFindNext", __delphirtti(Stdactns::TSearchFindNext)},
  {L"TSearchOption", __delphirtti(Ioutils::TSearchOption)},
//  {L"TSearchRec", __delphirtti(Sysutils::TSearchRec)},
  {L"TSearchReplace", __delphirtti(Stdactns::TSearchReplace)},
  {L"TSectionEvent", __delphirtti(Extctrls::TSectionEvent)},
  {L"TSeekOrigin", __delphirtti(Classes::TSeekOrigin)},
  {L"TSelectCellEvent", __delphirtti(Grids::TSelectCellEvent)},
//  {L"TSelection", __delphirtti(Stdctrls::TSelection)},
  {L"TSemaphore", __delphirtti(Syncobjs::TSemaphore)},
  {L"TSendMail", __delphirtti(Extactns::TSendMail)},
  {L"TSetEditEvent", __delphirtti(Grids::TSetEditEvent)},
  {L"TSetLayeredWindowAttributes", __delphirtti(Forms::TSetLayeredWindowAttributes)},
  {L"TSetNameEvent", __delphirtti(Classes::TSetNameEvent)},
  {L"TSettingChangeEvent", __delphirtti(Forms::TSettingChangeEvent)},
  {L"TShape", __delphirtti(Extctrls::TShape)},
  {L"TShapeType", __delphirtti(Extctrls::TShapeType)},
  {L"TSharedImage", __delphirtti(Graphics::TSharedImage)},
  {L"TShiftState", __delphirtti(Classes::TShiftState)},
  {L"TShortCut", __delphirtti(Classes::TShortCut)},
  {L"TShortCutEvent", __delphirtti(Forms::TShortCutEvent)},
  {L"TShortCutList", __delphirtti(Actnlist::TShortCutList)},
	{L"TShortIntDynArray", __delphirtti(System::TShortIntDynArray)},
  {L"TShowAction", __delphirtti(Forms::TShowAction)},
  {L"TShowCmd", __delphirtti(Extactns::TShowCmd)},
	{L"TShowHintEvent", __delphirtti(Forms::TShowHintEvent)},
  {L"TSimpleEvent", __delphirtti(Syncobjs::TSimpleEvent)},
  {L"TSimpleRWSync", __delphirtti(Sysutils::TSimpleRWSync)},
	{L"TSingleDynArray", __delphirtti(System::TSingleDynArray)},
  {L"TSingletonImplementation", __delphirtti(Generics_defaults::TSingletonImplementation)},
	{L"TSizeConstraints", __delphirtti(Controls::TSizeConstraints)},
	{L"TSizeStyle", __delphirtti(Extctrls::TSizeStyle)},
	{L"TSizingOrientation", __delphirtti(Toolwin::TSizingOrientation)},
//  {L"TSmallBlockTypeState", __delphirtti(System::TSmallBlockTypeState)},
//  {L"TSmallBlockTypeStates", __delphirtti(System::TSmallBlockTypeStates)},
	{L"TSmallIntDynArray", __delphirtti(System::TSmallIntDynArray)},
//  {L"TSmallPoint", __delphirtti(Types::TSmallPoint)},
  {L"TSoundexIntLength", __delphirtti(Strutils::TSoundexIntLength)},
  {L"TSoundexLength", __delphirtti(Strutils::TSoundexLength)},
  {L"TSpeedButton", __delphirtti(Buttons::TSpeedButton)},
  {L"TSpeedButtonActionLink", __delphirtti(Buttons::TSpeedButtonActionLink)},
//  {L"TSpinLock", __delphirtti(Syncobjs::TSpinLock)},
//  {L"TSpinWait", __delphirtti(Syncobjs::TSpinWait)},
  {L"TSplitRectType", __delphirtti(Types::TSplitRectType)},
  {L"TSplitter", __delphirtti(Extctrls::TSplitter)},
  {L"TSplitterCanResizeEvent", __delphirtti(Extctrls::TSplitterCanResizeEvent)},
  {L"TStack", __delphirtti(Contnrs::TStack)},
  {L"TStandardGestures", __delphirtti(Controls::TStandardGestures)},
  {L"TStartDockEvent", __delphirtti(Controls::TStartDockEvent)},
  {L"TStartDragEvent", __delphirtti(Controls::TStartDragEvent)},
  {L"TStaticBorderStyle", __delphirtti(Stdctrls::TStaticBorderStyle)},
  {L"TStaticListAction", __delphirtti(Listactns::TStaticListAction)},
  {L"TStaticListItems", __delphirtti(Listactns::TStaticListItems)},
  {L"TStaticText", __delphirtti(Stdctrls::TStaticText)},
//	{L"TStopwatch", __delphirtti(Diagnostics::TStopwatch)},
  {L"TStream", __delphirtti(Classes::TStream)},
  {L"TStreamAdapter", __delphirtti(Classes::TStreamAdapter)},
  {L"TStreamOriginalFormat", __delphirtti(Classes::TStreamOriginalFormat)},
  {L"TStreamOwnership", __delphirtti(Classes::TStreamOwnership)},
	{L"TStreamProc", __delphirtti(Classes::TStreamProc)},
  {L"TStreamReader", __delphirtti(Classes::TStreamReader)},
	{L"TStreamWriter", __delphirtti(Classes::TStreamWriter)},
  {L"TStringBuilder", __delphirtti(Sysutils::TStringBuilder)},
  {L"TStringComparer", __delphirtti(Generics_defaults::TStringComparer)},
	{L"TStringDynArray", __delphirtti(System::TStringDynArray)},
  {L"TStringGrid", __delphirtti(Grids::TStringGrid)},
  {L"TStringGridStrings", __delphirtti(Grids::TStringGridStrings)},
  {L"TStringHash", __delphirtti(Inifiles::TStringHash)},
//  {L"TStringItem", __delphirtti(Classes::TStringItem)},
//  {L"TStringItemList", __delphirtti(Classes::TStringItemList)},
  {L"TStringList", __delphirtti(Classes::TStringList)},
  {L"TStringListSortCompare", __delphirtti(Classes::TStringListSortCompare)},
  {L"TStringReader", __delphirtti(Classes::TStringReader)},
  {L"TStringSeachOption", __delphirtti(Strutils::TStringSeachOption)},
  {L"TStringSearchOptions", __delphirtti(Strutils::TStringSearchOptions)},
  {L"TStringStream", __delphirtti(Classes::TStringStream)},
  {L"TStringWriter", __delphirtti(Classes::TStringWriter)},
  {L"TStrings", __delphirtti(Classes::TStrings)},
  {L"TStringsDefined", __delphirtti(Classes::TStringsDefined)},
  {L"TStringsEnumerator", __delphirtti(Classes::TStringsEnumerator)},
//  {L"TSymLinkRec", __delphirtti(Sysutils::TSymLinkRec)},
  {L"TSynchroObject", __delphirtti(Syncobjs::TSynchroObject)},
  {L"TSysCharSet", __delphirtti(Sysutils::TSysCharSet)},
  {L"TSysLinkEvent", __delphirtti(Extctrls::TSysLinkEvent)},
  {L"TSysLinkType", __delphirtti(Extctrls::TSysLinkType)},
//  {L"TSysLocale", __delphirtti(Sysutils::TSysLocale)},
  {L"TSystemThreadEndProc", __delphirtti(System::TSystemThreadEndProc)},
  {L"TSystemThreadFuncProc", __delphirtti(System::TSystemThreadFuncProc)},
	{L"TTabAction", __delphirtti(Extactns::TTabAction)},
  {L"TTabChangeEvent", __delphirtti(Tabs::TTabChangeEvent)},
	{L"TTabDockPanel", __delphirtti(Docktabset::TTabDockPanel)},
  {L"TTabDockPanelClass", __delphirtti(Docktabset::TTabDockPanelClass)},
  {L"TTabList", __delphirtti(Tabs::TTabList)},
  {L"TTabOrder", __delphirtti(Controls::TTabOrder)},
  {L"TTabSet", __delphirtti(Tabs::TTabSet)},
  {L"TTabSetDrawTabEvent", __delphirtti(Tabs::TTabSetDrawTabEvent)},
  {L"TTabSetTabStyle", __delphirtti(Tabs::TTabSetTabStyle)},
  {L"TTabletOption", __delphirtti(Controls::TTabletOption)},
  {L"TTabletOptions", __delphirtti(Controls::TTabletOptions)},
  {L"TTaskDialog", __delphirtti(Dialogs::TTaskDialog)},
  {L"TTaskDialogBaseButtonItem", __delphirtti(Dialogs::TTaskDialogBaseButtonItem)},
  {L"TTaskDialogButtonItem", __delphirtti(Dialogs::TTaskDialogButtonItem)},
  {L"TTaskDialogButtonList", __delphirtti(Dialogs::TTaskDialogButtonList)},
  {L"TTaskDialogButtons", __delphirtti(Dialogs::TTaskDialogButtons)},
  {L"TTaskDialogButtonsEnumerator", __delphirtti(Dialogs::TTaskDialogButtonsEnumerator)},
  {L"TTaskDialogCommonButton", __delphirtti(Dialogs::TTaskDialogCommonButton)},
  {L"TTaskDialogCommonButtons", __delphirtti(Dialogs::TTaskDialogCommonButtons)},
  {L"TTaskDialogFlag", __delphirtti(Dialogs::TTaskDialogFlag)},
  {L"TTaskDialogFlags", __delphirtti(Dialogs::TTaskDialogFlags)},
  {L"TTaskDialogIcon", __delphirtti(Dialogs::TTaskDialogIcon)},
  {L"TTaskDialogProgressBar", __delphirtti(Dialogs::TTaskDialogProgressBar)},
  {L"TTaskDialogRadioButtonItem", __delphirtti(Dialogs::TTaskDialogRadioButtonItem)},
  {L"TTaskDlgClickEvent", __delphirtti(Dialogs::TTaskDlgClickEvent)},
  {L"TTaskDlgTimerEvent", __delphirtti(Dialogs::TTaskDlgTimerEvent)},
  {L"TTerminateProc", __delphirtti(Sysutils::TTerminateProc)},
//  {L"TTextBuf", __delphirtti(System::TTextBuf)},
  {L"TTextFormat", __delphirtti(Graphics::TTextFormat)},
	{L"TTextFormats", __delphirtti(Graphics::TTextFormats)},
	{L"TTextIOFunc", __delphirtti(System::TTextIOFunc)},
	{L"TTextLayout", __delphirtti(Stdctrls::TTextLayout)},
  {L"TTextLineBreakStyle", __delphirtti(System::TTextLineBreakStyle)},
  {L"TTextReader", __delphirtti(Classes::TTextReader)},
//  {L"TTextRec", __delphirtti(System::TTextRec)},
  {L"TTextWriter", __delphirtti(Classes::TTextWriter)},
//	{L"TThemeData", __delphirtti(Themes::TThemeData)},
  {L"TThemeServices", __delphirtti(Themes::TThemeServices)},
  {L"TThemeServicesClass", __delphirtti(Themes::TThemeServicesClass)},
  {L"TThemedButton", __delphirtti(Themes::TThemedButton)},
  {L"TThemedClock", __delphirtti(Themes::TThemedClock)},
  {L"TThemedComboBox", __delphirtti(Themes::TThemedComboBox)},
  {L"TThemedEdit", __delphirtti(Themes::TThemedEdit)},
  {L"TThemedElement", __delphirtti(Themes::TThemedElement)},
//  {L"TThemedElementDetails", __delphirtti(Themes::TThemedElementDetails)},
  {L"TThemedExplorerBar", __delphirtti(Themes::TThemedExplorerBar)},
  {L"TThemedHeader", __delphirtti(Themes::TThemedHeader)},
  {L"TThemedListview", __delphirtti(Themes::TThemedListview)},
  {L"TThemedMenu", __delphirtti(Themes::TThemedMenu)},
  {L"TThemedPage", __delphirtti(Themes::TThemedPage)},
  {L"TThemedProgress", __delphirtti(Themes::TThemedProgress)},
  {L"TThemedRebar", __delphirtti(Themes::TThemedRebar)},
  {L"TThemedScrollBar", __delphirtti(Themes::TThemedScrollBar)},
  {L"TThemedSpin", __delphirtti(Themes::TThemedSpin)},
  {L"TThemedStartPanel", __delphirtti(Themes::TThemedStartPanel)},
  {L"TThemedStatus", __delphirtti(Themes::TThemedStatus)},
  {L"TThemedTab", __delphirtti(Themes::TThemedTab)},
  {L"TThemedTaskBand", __delphirtti(Themes::TThemedTaskBand)},
	{L"TThemedTaskBar", __delphirtti(Themes::TThemedTaskBar)},
	{L"TThemedToolBar", __delphirtti(Themes::TThemedToolBar)},
	{L"TThemedToolTip", __delphirtti(Themes::TThemedToolTip)},
  {L"TThemedTrackBar", __delphirtti(Themes::TThemedTrackBar)},
  {L"TThemedTrayNotify", __delphirtti(Themes::TThemedTrayNotify)},
  {L"TThemedTreeview", __delphirtti(Themes::TThemedTreeview)},
  {L"TThemedWindow", __delphirtti(Themes::TThemedWindow)},
  {L"TThread", __delphirtti(Classes::TThread)},
//  {L"TThread.PSynchronizeRecord", __delphirtti(Classes_tthread::TThread.PSynchronizeRecord)},
//  {L"TThread.TSynchronizeRecord", __delphirtti(Classes_tthread::TThread.TSynchronizeRecord)},
  {L"TThreadFunc", __delphirtti(System::TThreadFunc)},
//  {L"TThreadInfo", __delphirtti(Sysutils::TThreadInfo)},
  {L"TThreadList", __delphirtti(Classes::TThreadList)},
  {L"TThreadLocalCounter", __delphirtti(Sysutils::TThreadLocalCounter)},
  {L"TThreadMethod", __delphirtti(Classes::TThreadMethod)},
  {L"TThreadPriority", __delphirtti(Classes::TThreadPriority)},
//  {L"TThreadProcedure", __delphirtti(Classes::TThreadProcedure)},
  {L"TTileMode", __delphirtti(Forms::TTileMode)},
  {L"TTime", __delphirtti(System::TTime)},
//  {L"TTimeSpan", __delphirtti(Timespan::TTimeSpan)},
//  {L"TTimeStamp", __delphirtti(Sysutils::TTimeStamp)},
  {L"TTimeZone", __delphirtti(Dateutils::TTimeZone)},
  {L"TTimer", __delphirtti(Extctrls::TTimer)},
	{L"TTimerMode", __delphirtti(Forms::TTimerMode)},
  {L"TToolDockForm", __delphirtti(Toolwin::TToolDockForm)},
  {L"TToolDockObject", __delphirtti(Toolwin::TToolDockObject)},
  {L"TToolWindow", __delphirtti(Toolwin::TToolWindow)},
  {L"TTopBottom", __delphirtti(Classes::TTopBottom)},
  {L"TTouchManager", __delphirtti(Controls::TTouchManager)},
	{L"TTouchProperty", __delphirtti(Controls::TTouchProperty)},
	{L"TTrackButton", __delphirtti(Menus::TTrackButton)},
	{L"TTransparentMode", __delphirtti(Graphics::TTransparentMode)},
  {L"TTrayIcon", __delphirtti(Extctrls::TTrayIcon)},
//  {L"TTypeTable", __delphirtti(System::TTypeTable)},
  {L"TUCS4CharArray", __delphirtti(System::TUCS4CharArray)},
  {L"TURLAction", __delphirtti(Extactns::TURLAction)},
  {L"TURLDownloadStatus", __delphirtti(Extactns::TURLDownloadStatus)},
  {L"TUTF7Encoding", __delphirtti(Sysutils::TUTF7Encoding)},
  {L"TUTF8Encoding", __delphirtti(Sysutils::TUTF8Encoding)},
  {L"TUnDockEvent", __delphirtti(Controls::TUnDockEvent)},
  {L"TUncertainState", __delphirtti(Sysutils::TUncertainState)},
	{L"TUnicodeBreak", __delphirtti(Character::TUnicodeBreak)},
  {L"TUnicodeCategory", __delphirtti(Character::TUnicodeCategory)},
  {L"TUnicodeEncoding", __delphirtti(Sysutils::TUnicodeEncoding)},
  {L"TUpdateEvent", __delphirtti(Imouse::TUpdateEvent)},
  {L"TValidatePackageProc", __delphirtti(Sysutils::TValidatePackageProc)},
  {L"TValidateTabEvent", __delphirtti(Extactns::TValidateTabEvent)},
  {L"TValueListEditor", __delphirtti(Valedit::TValueListEditor)},
  {L"TValueListStrings", __delphirtti(Valedit::TValueListStrings)},
  {L"TValueRelationship", __delphirtti(Types::TValueRelationship)},
  {L"TValueSign", __delphirtti(Math::TValueSign)},
	{L"TValueType", __delphirtti(Classes::TValueType)},
//  {L"TVarArray", __delphirtti(System::TVarArray)},
//  {L"TVarArrayBound", __delphirtti(System::TVarArrayBound)},
//  {L"TVarArrayBoundArray", __delphirtti(System::TVarArrayBoundArray)},
//  {L"TVarArrayCoorArray", __delphirtti(System::TVarArrayCoorArray)},
  {L"TVarCompareResult", __delphirtti(Variants::TVarCompareResult)},
//	{L"TVarData", __delphirtti(TVarData)},
	{L"TVarDataArray", __delphirtti(Variants::TVarDataArray)},
	{L"TVarDispProc", __delphirtti(Variants::TVarDispProc)},
//  {L"TVarRec", __delphirtti(System::TVarRec)},
//  {L"TVarTypeToElementInfo", __delphirtti(Varutils::TVarTypeToElementInfo)},
//  {L"TVariantManager", __delphirtti(System::TVariantManager)},
  {L"TVariantRelationship", __delphirtti(Variants::TVariantRelationship)},
  {L"TVerticalAlignment", __delphirtti(Classes::TVerticalAlignment)},
  {L"TVirtualListAction", __delphirtti(Listactns::TVirtualListAction)},
//  {L"TVirtualMethodInterceptor.TInterceptInfo", __delphirtti(Rtti_tvirtualmethodinterceptor::TVirtualMethodInterceptor.TInterceptInfo)},
  {L"TVisibilityClasses", __delphirtti(System::TVisibilityClasses)},
  {L"TWICImage", __delphirtti(Graphics::TWICImage)},
  {L"TWICImageFormat", __delphirtti(Graphics::TWICImageFormat)},
  {L"TWaitResult", __delphirtti(Syncobjs::TWaitResult)},
//  {L"TWideStringDynArray", __delphirtti(Types::TWideStringDynArray)},
//	{L"TWideStringItem", __delphirtti(Widestrings::TWideStringItem)},
//  {L"TWideStringItemList", __delphirtti(Widestrings::TWideStringItemList)},
  {L"TWideStringList", __delphirtti(Widestrings::TWideStringList)},
  {L"TWideStringListSortCompare", __delphirtti(Widestrings::TWideStringListSortCompare)},
  {L"TWideStrings", __delphirtti(Widestrings::TWideStrings)},
  {L"TWideStringsEnumerator", __delphirtti(Widestrings::TWideStringsEnumerator)},
  {L"TWinControl", __delphirtti(Controls::TWinControl)},
	{L"TWinControlActionLink", __delphirtti(Controls::TWinControlActionLink)},
  {L"TWinControlActionLinkClass", __delphirtti(Controls::TWinControlActionLinkClass)},
  {L"TWinControlClass", __delphirtti(Controls::TWinControlClass)},
  {L"TWindowAction", __delphirtti(Stdactns::TWindowAction)},
  {L"TWindowArrange", __delphirtti(Stdactns::TWindowArrange)},
  {L"TWindowCascade", __delphirtti(Stdactns::TWindowCascade)},
  {L"TWindowClose", __delphirtti(Stdactns::TWindowClose)},
  {L"TWindowHook", __delphirtti(Forms::TWindowHook)},
	{L"TWindowMinimizeAll", __delphirtti(Stdactns::TWindowMinimizeAll)},
	{L"TWindowState", __delphirtti(Forms::TWindowState)},
	{L"TWindowTileHorizontal", __delphirtti(Stdactns::TWindowTileHorizontal)},
  {L"TWindowTileVertical", __delphirtti(Stdactns::TWindowTileVertical)},
  {L"TWndMethod", __delphirtti(Classes::TWndMethod)},
//  {L"TWordArray", __delphirtti(Sysutils::TWordArray)},
//  {L"TWordDynArray", __delphirtti(Types::TWordDynArray)},
  {L"TWriter", __delphirtti(Classes::TWriter)},
  {L"TWriterProc", __delphirtti(Classes::TWriterProc)},
  {L"TZAlloc", __delphirtti(Zlib::TZAlloc)},
  {L"TZCompressionLevel", __delphirtti(Zlib::TZCompressionLevel)},
	{L"TZCompressionStream", __delphirtti(Zlib::TZCompressionStream)},
	{L"TZDecompressionStream", __delphirtti(Zlib::TZDecompressionStream)},
	{L"TZFree", __delphirtti(Zlib::TZFree)},
//  {L"TZStreamRec", __delphirtti(Zlib::TZStreamRec)},
	{L"UCS4Char", __delphirtti(System::UCS4Char)},
	{L"UCS4String", __delphirtti(System::UCS4String)},
//  {L"UInt64", __delphirtti(System::UInt64)},
	{L"UTF8String", __delphirtti(System::UTF8String)},
//  {L"UnitEntryTable", __delphirtti(System::UnitEntryTable)},
	{L"Variant", __delphirtti(System::Variant)},
  {L"WideString", __delphirtti(System::WideString)},
  {L"Word", __delphirtti(System::Word)},
  {L"WordBool", __delphirtti(System::WordBool)},
//  {L"WordRec", __delphirtti(Sysutils::WordRec)},
//  {L"dliNotification", __delphirtti(System::dliNotification)},
//  {L"in_addr", __delphirtti(Winsock::in_addr)},
//  {L"sockaddr_in", __delphirtti(Winsock::sockaddr_in)},
//  {L"string", __delphirtti(System::string)},
//	{L"tagSIZE", __delphirtti(Types::tagSIZE)},
};

TTypeInfo* LookUpClass(const String &Name)
{
	unsigned Count = sizeof(ClassList)/sizeof(ClassList[0]);
	for(unsigned I = 0; I < Count; I++)
		if(Name == ClassList[I].ClassName)
			return ClassList[I].TypeInfo;
	throw Exception("Class " + Name + " not found.");
}
} //namespace Python

