<div id="menu">
<img src="Graph.png" width="128" height="128" alt="Logo">
<p><font size="+1">
<a href=".">Main</a><br>
<a href="History.php">History</a><br>
<a href="Download.php">Download</a><br>
<a href="Beta.php">Beta</a><br>
<a href="Features.php">Features</a><br>
<a href="shots/Shot1.php">Screenshots</a><br>
<a href="Faq.php">FAQ</a><br>
<a href="/forum">Forum</a><br>
<a href="Language.php">Translations</a><br>
<a href="Donation.php">Donate</a><br>
<a href="Links.php">Links</a><br>
</font>
</p>
<p><a href="http://sf.net/projects/graph"><img src="sflogo.png" width="88" height="31" border="0" alt="SourceForge"></a></p>
</div>
