<div id="menu">
<img src="Graph.png" width="64" height="64" alt="Logo">
<p><font size="+1">
<a href=".">Main</a><br>
<a href="History.php">History</a><br>
<a href="Download.php">Download</a><br>
<a href="Beta.php">Beta</a><br>
<a href="Features.php">Features</a><br>
<a href="shots/Shot1.php">Screenshots</a><br>
<a href="Faq.php">FAQ</a><br>
<a href="http://news.gmane.org/gmane.comp.mathematics.graph">Forum</a><br>
<a href="Forum.php"> Support</a><br>
<a href="Language.php">Translations</a><br>
<a href="Donation.php">Donate</a><br>
<a href="Links.php">Links</a><br>
<a href="&#109;&#97;&#105;&#x6c;&#x74;&#111;&#x3a;&#103;&#x72;&#x61;&#x70;&#x68;&#64;&#112;&#x61;&#x64;&#x6f;&#119;&#97;&#x6e;&#x2e;&#x64;&#x6b;">Email</a>
</font>
</p>
<p><a href="http://sf.net/projects/graph"><img src="sflogo.png" width="88" height="31" border="0" alt="SourceForge"></a></p>
</div>
