# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Swig', [dirname(__file__)])
        except ImportError:
            import _Swig
            return _Swig
        if fp is not None:
            try:
                _mod = imp.load_module('_Swig', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _Swig = swig_import_helper()
    del swig_import_helper
else:
    import _Swig
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def GetAxes() -> "Graph::TAxes *" :
  return _Swig.GetAxes()
GetAxes = _Swig.GetAxes

def Redraw() -> "void" :
  return _Swig.Redraw()
Redraw = _Swig.Redraw
Radian = _Swig.Radian
Degree = _Swig.Degree
asNone = _Swig.asNone
asCrossed = _Swig.asCrossed
asBoxed = _Swig.asBoxed
lpCustom = _Swig.lpCustom
lpTopRight = _Swig.lpTopRight
lpBottomRight = _Swig.lpBottomRight
lpTopLeft = _Swig.lpTopLeft
lpBottomLeft = _Swig.lpBottomLeft
class TAxis(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TAxis, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TAxis, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_setmethods__["Min"] = _Swig.TAxis_Min_set
    __swig_getmethods__["Min"] = _Swig.TAxis_Min_get
    if _newclass:Min = _swig_property(_Swig.TAxis_Min_get, _Swig.TAxis_Min_set)
    __swig_setmethods__["Max"] = _Swig.TAxis_Max_set
    __swig_getmethods__["Max"] = _Swig.TAxis_Max_get
    if _newclass:Max = _swig_property(_Swig.TAxis_Max_get, _Swig.TAxis_Max_set)
    __swig_setmethods__["LogScl"] = _Swig.TAxis_LogScl_set
    __swig_getmethods__["LogScl"] = _Swig.TAxis_LogScl_get
    if _newclass:LogScl = _swig_property(_Swig.TAxis_LogScl_get, _Swig.TAxis_LogScl_set)
    __swig_setmethods__["MultiplyOfPi"] = _Swig.TAxis_MultiplyOfPi_set
    __swig_getmethods__["MultiplyOfPi"] = _Swig.TAxis_MultiplyOfPi_get
    if _newclass:MultiplyOfPi = _swig_property(_Swig.TAxis_MultiplyOfPi_get, _Swig.TAxis_MultiplyOfPi_set)
    __swig_setmethods__["ShowLabel"] = _Swig.TAxis_ShowLabel_set
    __swig_getmethods__["ShowLabel"] = _Swig.TAxis_ShowLabel_get
    if _newclass:ShowLabel = _swig_property(_Swig.TAxis_ShowLabel_get, _Swig.TAxis_ShowLabel_set)
    __swig_setmethods__["ShowNumbers"] = _Swig.TAxis_ShowNumbers_set
    __swig_getmethods__["ShowNumbers"] = _Swig.TAxis_ShowNumbers_get
    if _newclass:ShowNumbers = _swig_property(_Swig.TAxis_ShowNumbers_get, _Swig.TAxis_ShowNumbers_set)
    __swig_setmethods__["ShowTicks"] = _Swig.TAxis_ShowTicks_set
    __swig_getmethods__["ShowTicks"] = _Swig.TAxis_ShowTicks_get
    if _newclass:ShowTicks = _swig_property(_Swig.TAxis_ShowTicks_get, _Swig.TAxis_ShowTicks_set)
    __swig_setmethods__["ShowGrid"] = _Swig.TAxis_ShowGrid_set
    __swig_getmethods__["ShowGrid"] = _Swig.TAxis_ShowGrid_get
    if _newclass:ShowGrid = _swig_property(_Swig.TAxis_ShowGrid_get, _Swig.TAxis_ShowGrid_set)
    __swig_setmethods__["AutoTick"] = _Swig.TAxis_AutoTick_set
    __swig_getmethods__["AutoTick"] = _Swig.TAxis_AutoTick_get
    if _newclass:AutoTick = _swig_property(_Swig.TAxis_AutoTick_get, _Swig.TAxis_AutoTick_set)
    __swig_setmethods__["AutoGrid"] = _Swig.TAxis_AutoGrid_set
    __swig_getmethods__["AutoGrid"] = _Swig.TAxis_AutoGrid_get
    if _newclass:AutoGrid = _swig_property(_Swig.TAxis_AutoGrid_get, _Swig.TAxis_AutoGrid_set)
    __swig_setmethods__["Label"] = _Swig.TAxis_Label_set
    __swig_getmethods__["Label"] = _Swig.TAxis_Label_get
    if _newclass:Label = _swig_property(_Swig.TAxis_Label_get, _Swig.TAxis_Label_set)
    __swig_setmethods__["AxisCross"] = _Swig.TAxis_AxisCross_set
    __swig_getmethods__["AxisCross"] = _Swig.TAxis_AxisCross_get
    if _newclass:AxisCross = _swig_property(_Swig.TAxis_AxisCross_get, _Swig.TAxis_AxisCross_set)
    __swig_setmethods__["TickUnit"] = _Swig.TAxis_TickUnit_set
    __swig_getmethods__["TickUnit"] = _Swig.TAxis_TickUnit_get
    if _newclass:TickUnit = _swig_property(_Swig.TAxis_TickUnit_get, _Swig.TAxis_TickUnit_set)
    __swig_setmethods__["GridUnit"] = _Swig.TAxis_GridUnit_set
    __swig_getmethods__["GridUnit"] = _Swig.TAxis_GridUnit_get
    if _newclass:GridUnit = _swig_property(_Swig.TAxis_GridUnit_get, _Swig.TAxis_GridUnit_set)
TAxis_swigregister = _Swig.TAxis_swigregister
TAxis_swigregister(TAxis)

aaNone = _Swig.aaNone
aaPositiveEnd = _Swig.aaPositiveEnd
aaBothEnds = _Swig.aaBothEnds
npCenter = _Swig.npCenter
npBefore = _Swig.npBefore
gsLines = _Swig.gsLines
gsDots = _Swig.gsDots
class TAxes(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TAxes, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TAxes, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_setmethods__["xAxis"] = _Swig.TAxes_xAxis_set
    __swig_getmethods__["xAxis"] = _Swig.TAxes_xAxis_get
    if _newclass:xAxis = _swig_property(_Swig.TAxes_xAxis_get, _Swig.TAxes_xAxis_set)
    __swig_setmethods__["yAxis"] = _Swig.TAxes_yAxis_set
    __swig_getmethods__["yAxis"] = _Swig.TAxes_yAxis_get
    if _newclass:yAxis = _swig_property(_Swig.TAxes_yAxis_get, _Swig.TAxes_yAxis_set)
    __swig_setmethods__["AxesColor"] = _Swig.TAxes_AxesColor_set
    __swig_getmethods__["AxesColor"] = _Swig.TAxes_AxesColor_get
    if _newclass:AxesColor = _swig_property(_Swig.TAxes_AxesColor_get, _Swig.TAxes_AxesColor_set)
    __swig_setmethods__["GridColor"] = _Swig.TAxes_GridColor_set
    __swig_getmethods__["GridColor"] = _Swig.TAxes_GridColor_get
    if _newclass:GridColor = _swig_property(_Swig.TAxes_GridColor_get, _Swig.TAxes_GridColor_set)
    __swig_setmethods__["BackgroundColor"] = _Swig.TAxes_BackgroundColor_set
    __swig_getmethods__["BackgroundColor"] = _Swig.TAxes_BackgroundColor_get
    if _newclass:BackgroundColor = _swig_property(_Swig.TAxes_BackgroundColor_get, _Swig.TAxes_BackgroundColor_set)
    __swig_getmethods__["NumberFont"] = _Swig.TAxes_NumberFont_get
    if _newclass:NumberFont = _swig_property(_Swig.TAxes_NumberFont_get)
    __swig_getmethods__["LabelFont"] = _Swig.TAxes_LabelFont_get
    if _newclass:LabelFont = _swig_property(_Swig.TAxes_LabelFont_get)
    __swig_getmethods__["LegendFont"] = _Swig.TAxes_LegendFont_get
    if _newclass:LegendFont = _swig_property(_Swig.TAxes_LegendFont_get)
    __swig_setmethods__["Title"] = _Swig.TAxes_Title_set
    __swig_getmethods__["Title"] = _Swig.TAxes_Title_get
    if _newclass:Title = _swig_property(_Swig.TAxes_Title_get, _Swig.TAxes_Title_set)
    __swig_getmethods__["TitleFont"] = _Swig.TAxes_TitleFont_get
    if _newclass:TitleFont = _swig_property(_Swig.TAxes_TitleFont_get)
    __swig_setmethods__["ShowLegend"] = _Swig.TAxes_ShowLegend_set
    __swig_getmethods__["ShowLegend"] = _Swig.TAxes_ShowLegend_get
    if _newclass:ShowLegend = _swig_property(_Swig.TAxes_ShowLegend_get, _Swig.TAxes_ShowLegend_set)
    __swig_setmethods__["Trigonometry"] = _Swig.TAxes_Trigonometry_set
    __swig_getmethods__["Trigonometry"] = _Swig.TAxes_Trigonometry_get
    if _newclass:Trigonometry = _swig_property(_Swig.TAxes_Trigonometry_get, _Swig.TAxes_Trigonometry_set)
    __swig_setmethods__["AxesStyle"] = _Swig.TAxes_AxesStyle_set
    __swig_getmethods__["AxesStyle"] = _Swig.TAxes_AxesStyle_get
    if _newclass:AxesStyle = _swig_property(_Swig.TAxes_AxesStyle_get, _Swig.TAxes_AxesStyle_set)
    __swig_setmethods__["LegendPlacement"] = _Swig.TAxes_LegendPlacement_set
    __swig_getmethods__["LegendPlacement"] = _Swig.TAxes_LegendPlacement_get
    if _newclass:LegendPlacement = _swig_property(_Swig.TAxes_LegendPlacement_get, _Swig.TAxes_LegendPlacement_set)
    __swig_setmethods__["LegendPos"] = _Swig.TAxes_LegendPos_set
    __swig_getmethods__["LegendPos"] = _Swig.TAxes_LegendPos_get
    if _newclass:LegendPos = _swig_property(_Swig.TAxes_LegendPos_get, _Swig.TAxes_LegendPos_set)
    __swig_setmethods__["GridSize"] = _Swig.TAxes_GridSize_set
    __swig_getmethods__["GridSize"] = _Swig.TAxes_GridSize_get
    if _newclass:GridSize = _swig_property(_Swig.TAxes_GridSize_get, _Swig.TAxes_GridSize_set)
    __swig_setmethods__["CalcComplex"] = _Swig.TAxes_CalcComplex_set
    __swig_getmethods__["CalcComplex"] = _Swig.TAxes_CalcComplex_get
    if _newclass:CalcComplex = _swig_property(_Swig.TAxes_CalcComplex_get, _Swig.TAxes_CalcComplex_set)
    __swig_setmethods__["AxesArrows"] = _Swig.TAxes_AxesArrows_set
    __swig_getmethods__["AxesArrows"] = _Swig.TAxes_AxesArrows_get
    if _newclass:AxesArrows = _swig_property(_Swig.TAxes_AxesArrows_get, _Swig.TAxes_AxesArrows_set)
    __swig_setmethods__["NumberPlacement"] = _Swig.TAxes_NumberPlacement_set
    __swig_getmethods__["NumberPlacement"] = _Swig.TAxes_NumberPlacement_get
    if _newclass:NumberPlacement = _swig_property(_Swig.TAxes_NumberPlacement_get, _Swig.TAxes_NumberPlacement_set)
    __swig_setmethods__["GridStyle"] = _Swig.TAxes_GridStyle_set
    __swig_getmethods__["GridStyle"] = _Swig.TAxes_GridStyle_get
    if _newclass:GridStyle = _swig_property(_Swig.TAxes_GridStyle_get, _Swig.TAxes_GridStyle_set)
TAxes_swigregister = _Swig.TAxes_swigregister
TAxes_swigregister(TAxes)

class TDefaultData(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TDefaultData, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TDefaultData, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_setmethods__["Style"] = _Swig.TDefaultData_Style_set
    __swig_getmethods__["Style"] = _Swig.TDefaultData_Style_get
    if _newclass:Style = _swig_property(_Swig.TDefaultData_Style_get, _Swig.TDefaultData_Style_set)
    __swig_setmethods__["Color"] = _Swig.TDefaultData_Color_set
    __swig_getmethods__["Color"] = _Swig.TDefaultData_Color_get
    if _newclass:Color = _swig_property(_Swig.TDefaultData_Color_get, _Swig.TDefaultData_Color_set)
    __swig_setmethods__["Size"] = _Swig.TDefaultData_Size_set
    __swig_getmethods__["Size"] = _Swig.TDefaultData_Size_get
    if _newclass:Size = _swig_property(_Swig.TDefaultData_Size_get, _Swig.TDefaultData_Size_set)
TDefaultData_swigregister = _Swig.TDefaultData_swigregister
TDefaultData_swigregister(TDefaultData)

cfReal = _Swig.cfReal
cfRectangular = _Swig.cfRectangular
cfPolar = _Swig.cfPolar
class TProperty(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TProperty, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TProperty, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_setmethods__["RoundTo"] = _Swig.TProperty_RoundTo_set
    __swig_getmethods__["RoundTo"] = _Swig.TProperty_RoundTo_get
    if _newclass:RoundTo = _swig_property(_Swig.TProperty_RoundTo_get, _Swig.TProperty_RoundTo_set)
    __swig_setmethods__["SavePos"] = _Swig.TProperty_SavePos_set
    __swig_getmethods__["SavePos"] = _Swig.TProperty_SavePos_get
    if _newclass:SavePos = _swig_property(_Swig.TProperty_SavePos_get, _Swig.TProperty_SavePos_set)
    __swig_setmethods__["ComplexFormat"] = _Swig.TProperty_ComplexFormat_set
    __swig_getmethods__["ComplexFormat"] = _Swig.TProperty_ComplexFormat_get
    if _newclass:ComplexFormat = _swig_property(_Swig.TProperty_ComplexFormat_get, _Swig.TProperty_ComplexFormat_set)
    __swig_setmethods__["CheckForUpdate"] = _Swig.TProperty_CheckForUpdate_set
    __swig_getmethods__["CheckForUpdate"] = _Swig.TProperty_CheckForUpdate_get
    if _newclass:CheckForUpdate = _swig_property(_Swig.TProperty_CheckForUpdate_get, _Swig.TProperty_CheckForUpdate_set)
    __swig_setmethods__["DefaultFunction"] = _Swig.TProperty_DefaultFunction_set
    __swig_getmethods__["DefaultFunction"] = _Swig.TProperty_DefaultFunction_get
    if _newclass:DefaultFunction = _swig_property(_Swig.TProperty_DefaultFunction_get, _Swig.TProperty_DefaultFunction_set)
    __swig_setmethods__["DefaultPoint"] = _Swig.TProperty_DefaultPoint_set
    __swig_getmethods__["DefaultPoint"] = _Swig.TProperty_DefaultPoint_get
    if _newclass:DefaultPoint = _swig_property(_Swig.TProperty_DefaultPoint_get, _Swig.TProperty_DefaultPoint_set)
    __swig_setmethods__["DefaultPointLine"] = _Swig.TProperty_DefaultPointLine_set
    __swig_getmethods__["DefaultPointLine"] = _Swig.TProperty_DefaultPointLine_get
    if _newclass:DefaultPointLine = _swig_property(_Swig.TProperty_DefaultPointLine_get, _Swig.TProperty_DefaultPointLine_set)
    __swig_setmethods__["DefaultShade"] = _Swig.TProperty_DefaultShade_set
    __swig_getmethods__["DefaultShade"] = _Swig.TProperty_DefaultShade_get
    if _newclass:DefaultShade = _swig_property(_Swig.TProperty_DefaultShade_get, _Swig.TProperty_DefaultShade_set)
    __swig_setmethods__["DefaultTrendline"] = _Swig.TProperty_DefaultTrendline_set
    __swig_getmethods__["DefaultTrendline"] = _Swig.TProperty_DefaultTrendline_get
    if _newclass:DefaultTrendline = _swig_property(_Swig.TProperty_DefaultTrendline_get, _Swig.TProperty_DefaultTrendline_set)
    __swig_setmethods__["DefaultRelation"] = _Swig.TProperty_DefaultRelation_set
    __swig_getmethods__["DefaultRelation"] = _Swig.TProperty_DefaultRelation_get
    if _newclass:DefaultRelation = _swig_property(_Swig.TProperty_DefaultRelation_get, _Swig.TProperty_DefaultRelation_set)
    __swig_setmethods__["DefaultTangent"] = _Swig.TProperty_DefaultTangent_set
    __swig_getmethods__["DefaultTangent"] = _Swig.TProperty_DefaultTangent_get
    if _newclass:DefaultTangent = _swig_property(_Swig.TProperty_DefaultTangent_get, _Swig.TProperty_DefaultTangent_set)
    __swig_setmethods__["DefaultDif"] = _Swig.TProperty_DefaultDif_set
    __swig_getmethods__["DefaultDif"] = _Swig.TProperty_DefaultDif_get
    if _newclass:DefaultDif = _swig_property(_Swig.TProperty_DefaultDif_get, _Swig.TProperty_DefaultDif_set)
    __swig_setmethods__["DefaultPointLabelFont"] = _Swig.TProperty_DefaultPointLabelFont_set
    __swig_getmethods__["DefaultPointLabelFont"] = _Swig.TProperty_DefaultPointLabelFont_get
    if _newclass:DefaultPointLabelFont = _swig_property(_Swig.TProperty_DefaultPointLabelFont_get, _Swig.TProperty_DefaultPointLabelFont_set)
    __swig_setmethods__["DefaultLabelFont"] = _Swig.TProperty_DefaultLabelFont_set
    __swig_getmethods__["DefaultLabelFont"] = _Swig.TProperty_DefaultLabelFont_get
    if _newclass:DefaultLabelFont = _swig_property(_Swig.TProperty_DefaultLabelFont_get, _Swig.TProperty_DefaultLabelFont_set)
    __swig_setmethods__["ShowTipsAtStartup"] = _Swig.TProperty_ShowTipsAtStartup_set
    __swig_getmethods__["ShowTipsAtStartup"] = _Swig.TProperty_ShowTipsAtStartup_get
    if _newclass:ShowTipsAtStartup = _swig_property(_Swig.TProperty_ShowTipsAtStartup_get, _Swig.TProperty_ShowTipsAtStartup_set)
    __swig_setmethods__["NextTip"] = _Swig.TProperty_NextTip_set
    __swig_getmethods__["NextTip"] = _Swig.TProperty_NextTip_get
    if _newclass:NextTip = _swig_property(_Swig.TProperty_NextTip_get, _Swig.TProperty_NextTip_set)
    __swig_setmethods__["Language"] = _Swig.TProperty_Language_set
    __swig_getmethods__["Language"] = _Swig.TProperty_Language_get
    if _newclass:Language = _swig_property(_Swig.TProperty_Language_get, _Swig.TProperty_Language_set)
    __swig_setmethods__["FontScale"] = _Swig.TProperty_FontScale_set
    __swig_getmethods__["FontScale"] = _Swig.TProperty_FontScale_get
    if _newclass:FontScale = _swig_property(_Swig.TProperty_FontScale_get, _Swig.TProperty_FontScale_set)
    __swig_setmethods__["CustomDecimalSeparator"] = _Swig.TProperty_CustomDecimalSeparator_set
    __swig_getmethods__["CustomDecimalSeparator"] = _Swig.TProperty_CustomDecimalSeparator_get
    if _newclass:CustomDecimalSeparator = _swig_property(_Swig.TProperty_CustomDecimalSeparator_get, _Swig.TProperty_CustomDecimalSeparator_set)
    __swig_setmethods__["DecimalSeparator"] = _Swig.TProperty_DecimalSeparator_set
    __swig_getmethods__["DecimalSeparator"] = _Swig.TProperty_DecimalSeparator_get
    if _newclass:DecimalSeparator = _swig_property(_Swig.TProperty_DecimalSeparator_get, _Swig.TProperty_DecimalSeparator_set)
TProperty_swigregister = _Swig.TProperty_swigregister
TProperty_swigregister(TProperty)


cvar = _Swig.cvar
Property = cvar.Property

