<div id="menu"> 
<p><img src="Graph.png" width="64" height="64" alt="Logo"></p>
<p><font size="+1">  
<a href="index.php">Main</a><br>
<a href="History.php">History</a><br>
<a href="Download.php">Download</a><br>

<a href="Features.php">Features</a><br>
<a href="Shots.php">Screen shots</a><br>
<a href="Faq.php" target="mainFrame">FAQ</a><br>
<a href="http://news.gmane.org/gmane.comp.mathematics.graph" target="mainFrame">Forum</a><br>
  <a href="forum.html" target="mainFrame"> Support</a><br>
<a href="Language.php">Translations</a><br>
<a href="Donation.php">Donate</a><br>
<a href="Links.php">Links</a><br>
<a href="&#109;&#97;&#105;&#x6c;&#x74;&#111;&#x3a;&#103;&#x72;&#x61;&#x70;&#x68;&#64;&#112;&#x61;&#x64;&#x6f;&#119;&#97;&#x6e;&#x2e;&#x64;&#x6b;">E-mail</a> 
</font></p>
<p>&nbsp;</p>
<p><font size="+1">Visitors:</font></p>
<p>
<!-- Start på ZIP Stat kode -->
<script language="JavaScript" type="text/javascript">
<!--
far="Andre"; jav="Ved ikke"; skh="Andre"; jav=navigator.javaEnabled(); 
ref=""+escape(top.document.referrer); nav=navigator.appName;
if (navigator.appName == "Netscape" && (navigator.appVersion.charAt(0) == "2" || navigator.appVersion.charAt(0) == "3")) {skriv=false;} else {skriv=true;}
if (skriv==true) { skh=screen.width + "x" + screen.height;
if (nav != "Netscape"){far=screen.colorDepth;} else {far=screen.pixelDepth;}
puri="brugernavn=Padowan&amp;version=150&amp;ssto="+skh+"&amp;referer="+ref+"&amp;colors="+far+"&amp;java="+jav+"&amp;js=true&amp;billed=taelhs&amp;ntael=ja";
document.write("<img  border=\"0\" src=\"http://www.zipstat.dk/cgi-bin/zipstat/zipstat.cgi2?"+puri+"\" alt=\"\" align=left><\/a>"); }
//-->
</script>
</p>
<noscript> <img  border="0" src="http://www.zipstat.dk/cgi-bin/zipstat/zipstat.cgi2?brugernavn=Padowan&amp;js=false&amp;billed=taelhs&amp;ntael=ja" align=left alt="Counter"> 
</noscript> 
<!-- Slut på ZIP Stat kode -->
<p>&nbsp;</p>
<p><a href="http://sf.net/projects/graph" target="_top"><img src="sflogo.png" width="88" height="31" border="0"></a></p>
<p><img border="0"
        src="http://www.w3.org/Icons/valid-html401"
        alt="Valid HTML 4.01!" height="31" width="88"> </p>
</div>
